### ISSUE TITLE
Bug in DataAtmGridComp when running CICE6

### ISSUE THREAD

**Issue by zhaobin74** [GEOS-ESM/GEOSgcm_GridComp#1029]
When CICE6 is running, there is a ```SURFSTATE``` bundle connected between AGCM and  OGCM at GCM level. 
Currently, ```DataAtmGridComp``` terminated all children's imports. This is incorrect and it **should** allow ```SURFSTATE``` to propagate upwards.

Another issue is in ```finalize``` where a dealloc should only be called when CICE4 is used.

**Comment by mfmehari** [comment]
@zhaobin74 Thank you for making it work with CICE6, it was previously only tested with CICE4. Tested the changes you made with CICE4 and works fine.
