### ISSUE TITLE
Possible bug in gustiness calculation in surface

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GEOSgcm_GridComp#121]
In looking at #120, I saw this in various components. First, we fill `GST` (the pointer to the `GUST` export):
https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/108e99b34f79236cc1af198cbcffc2d8ae62384c/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_OpenWaterGridComp.F90#L2007
Then *AFTER* that we actually calculate `WW`:
https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/108e99b34f79236cc1af198cbcffc2d8ae62384c/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_OpenWaterGridComp.F90#L2020-L2021

I'm pretty sure this is a bug, but I'd like the input of @wmputman, @sanAkel, or Andrea (not yet on Github) before I submit the (obvious) fix.

**Comment by mathomp4** [comment]
Note: `WW` is in the internal state of, say, openwater. So I think we are essentially outputting the *last* step value of gustiness (combined with the current fraction?)

**Comment by sanAkel** [comment]
@wmputman This does indeed look incorrect! Seems it was indeed buggy (e.g., Jason-1_0_BETA ). 

1. Shall I absorb into whatever needs to be done to the interface layer? 
2. or, make a note and fix separately? @mathomp4, can submit the fix... 
3. Do a single forecast or a bunch of them to see how different are the answers? And then combine it with interface "fixes"?

**Comment by mathomp4** [comment]
I can easily fix it in my patch for #120, if wanted. I'm changing files in Surface often the same ones with the bug. (Some set `GUST` = 0.0 by fiat, and that's already good.) 

As far as I can tell `GUST` seems to be completely _diagnostic_ to the GCM (modulo some feature branch using it). Nothing has it as an import or in a connectivity so it's just there for HISTORY. The fact that I can fix the `GUST` bug or even set `GUST` to a constant and have the checkpoints all be zero-diff, supports this.

This might not be the case with the ADAS. I see a `gust` variable in `ana5sfc.F90` in Hermes. `ana5sfc.x` is then (possibly) used inside of `analyzer`. I've tried my best at reading `analyzer` and f525_fpp and I *think* we never actually exercise `ana5sfc.x` because `NOSFCANA` is set to 1? I'm way out of my depth with deep ADAS though.

The GEOSldas does seem to use it as an import (paging @JustinPerket and @gmao-rreichle). Well, maybe? It's inside `GEOSens_GridComp/GEOS_EnsGridComp.F90` where it's an import...but I don't see any `MAPL_AddImportSpec` calls at all in there. So hand-waving whatever magic is happening there (paging @atrayano), I think all it's doing is averaging the ensemble `GUST` so I think it's still diagnostic to the LDAS.

**Comment by mathomp4** [comment]
For future analysis, I think the issue is present in:
* `GEOS_CatchGridComp.F90`
* `GEOS_CatchCNGridComp.F90`
* `GEOS_OpenWaterGridComp.F90`
* `GEOS_CICE4ColumnPhysGridComp.F90`
* `GEOS_SimpleSeaiceGridComp.F90`

Lake and Landice seem to just set `GST = 0.0` and not even do much with `WW`. (I'd love someone to educate me as to why. You know...physically. :smiley:)

**Comment by gmao-rreichle** [comment]
Thanks for alerting me, @mathomp4 
As far as I know, the land doesn't use gustiness in any way.  I think gustiness appears in the GEOSldas GEOSens_GridComp simply because it's in the list of exports for GEOScatch_GridComp. 
I would definitely check with Andrea to make sure there is indeed a bug, and, if so, how it should be fixed.  There may be a reason for doing the calculations in this order.

**Comment by sanAkel** [comment]
@mathomp4

We use the anasfc.x in MERRA-2, and in any Merra fvsetup, (best of my
knowledge).

Physically “speaking” to me it’s a bug!

We should update all variables consistently! Maybe the gust has a
Logic that beats me!!
Will ask around.

**Comment by amolod** [comment]
Clearly the WW and using it to fill GST are in the wrong order. As of now noone is using GST so "no foul". But there is some new code for this (and the use of it) imminent (from Saulo that Santha has) so it should be discussed among a few folks.

**Comment by sanAkel** [comment]
@sdrabenh Would you be interested in getting this obvious fix bundled into a future non-zero diff change? Please read above, it will non-zero diff internal state, but not the model output. @mathomp4 Did I get that right?

**Comment by mathomp4** [comment]
@sanAkel I think that's right. If nothing is using `GST` yet, I guess it'd only affect the internal state? I'd probably need to test this to be sure.

**Comment by sanAkel** [comment]
👍 let us know @mathomp4, we can package this change with others, if that works for @sdrabenh

**Comment by amolod** [comment]
Good catch! GST (or GUST) and WW are indeed only diagnostic, as long as the (default) option is exercised to use helfsurface. WW goes to louissurface and changing this will impact the answer. unless all you want to do is "load" GST after the new WW is computed. i don't know how to see the proposed fix in github (sry).  Also, since FR really only changes in the ocean when there is sea ice (and land when snow), its a time truncation issue here. not a big impact on GUST, whoever was using it.

**Comment by sdrabenh** [comment]
Thanks all. I will consider this in the next none-0-diff iteration.

**Comment by mathomp4** [comment]
I have a PR now with #409 . I *think* I caught all the places where `GST` (aka `GUST`) depended on `WW` but was set before `WW` was calculated.

**Comment by yvikhlya** [comment]
@amolod 

> i don't know how to see the proposed fix in github (sry). 

You can see a proposed fix in pull request

https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/409/files

**Comment by amolod** [comment]
﻿thanks

-------------------------------
Andrea M. Molod, Ph.D.
Global Modeling and Assimilation Office
NASA Goddard Space Flight Center
Desk: 301-614-6845
-------------------------------
