### ISSUE TITLE
@sanakel write pseudo code

### ISSUE THREAD

**Issue by tclune** [GEOS-ESM/GEOSgcm_GridComp#139]

**Comment by sanAkel** [comment]
https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/142 

adds 1st draft of psuedo code

**Comment by sanAkel** [comment]
cleaned pseudo code and additions from @tclune (https://github.com/GEOS-ESM/GEOSgcm_GridComp/commit/24a77c28c31cf20d33a9f76341e2e95ea8bae88d) 

in https://github.com/GEOS-ESM/GEOSgcm_GridComp/tree/feature/sanAkel/dataAtm-revamp/GEOSdataatm_GridComp
