### ISSUE TITLE
Incorrect use of pointers in DataAtmGridComp

### ISSUE THREAD

**Issue by tclune** [GEOS-ESM/GEOSgcm_GridComp#140]
In the block of code below,   99 pointers are assigned to 3 targets.    The intent is clearly to have 99 independent arrays, but the result is 33 copies of each of 3 arrays with the first 32 copies of each case overwritten by the final iteration of the loop.

https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/05bf4235504b5b654dc2c388d6b7d5383b61f7fc/GEOSdataatm_GridComp/GEOS_DataAtmGridComp.F90#L2607-L2632

**Comment by sanAkel** [comment]
https://github.com/GEOS-ESM/GEOSgcm_GridComp/tree/24a77c28c31cf20d33a9f76341e2e95ea8bae88d

fixes this bug.
