### ISSUE TITLE
Import develop branch from developer

### ISSUE THREAD

**Issue by tclune** [GEOS-ESM/GEOSgcm_GridComp#15]
For the time being we need a long-lived branch that include the necessary interface changes to support development of MAPL.

The branch should be dev/MAPL and probably needs to be at least on Chem_GridComp as well.

Later we'll decide if this branch should be maintained by rebasing (clean for everyone else) or merges (less problematic for SI team)

**Comment by tclune** [comment]
I've made an initial attempt at this and decided on dev/MAPL-2.0 for the branch.

Sort of a brain dead branch off of the develop branch.  Overwrote all files with their versions on developer.  Deleted all CVS and GNUmakefile's and then did not stage any CMakefiles.

Biggest danger is if the develop branch should have deleted any files on developer, this branch does not reflect that.   If @mathomp4 knows a good way to check that it would not hurt.

I'm now going to do the same for Chemistry.

**Comment by mathomp4** [comment]
@bena-nasa has done this. `dev/MAPL-2.0` is up to developer
