### ISSUE TITLE
Add DataLake mode in the lake component

### ISSUE THREAD

**Issue by atrayano** [GEOS-ESM/GEOSgcm_GridComp#169]
The current lake model does not adequately predict the surface temperatures for certain lakes. In AMIP mode we use a workaround and label Great Lakes and Caspian Sea as being part of the ocean, and thus the SSTs are provided by DataSea component. This approach cannot be used in the coupled model, and therefore we keep 2 sets of tile file, and also creates restart incompatibility issues between AMPI and coupled restarts.

We need to add a new mode (DataLake) in the lake code which will provide SSTs over certain lakes (for example Great Lakes and Caspian Sea) for observed SSTs (either Reynolds or Ostia). The choice of which lakes are affected is controlled by a mask. provided in a separate file.

**Comment by sanAkel** [comment]
@atrayano please take a look at the code: https://github.com/GEOS-ESM/GMAO_Shared/pull/112 Thank you!

**Comment by atrayano** [comment]
@sdrabenh I am wondering if you had a chance to test this PR. The code is already "protected" so the default is not to use dataLake, and it should be zero diffs. For this test you do not need any adidtional files

**Comment by sanAkel** [comment]
> @sdrabenh I am wondering if you had a chance to test this PR. The code is already "protected" so the default is not to use dataLake, and it should be zero diffs. For this test you do not need any additional files

Someone also needs to test this feature by turning it "ON"! I understand when it is "OFF" i.e., default- it gives the same answers.

**Comment by sdrabenh** [comment]
@atrayano yes this is 0-diff as anticipated. I would like to turn this on for more testing. Do we have an appropriate mask yet similar to the existing mode (Great Lakes and Caspian Sea)? Or anything I can test?

**Comment by atrayano** [comment]
Thanks! I do not have any mask file at the moment, but I could try to generate one in the next couple of days

From: Scott Rabenhorst ***@***.***>
Reply-To: GEOS-ESM/GEOSgcm_GridComp ***@***.***>
Date: Tuesday, March 15, 2022 at 10:28 AM
To: GEOS-ESM/GEOSgcm_GridComp ***@***.***>
Cc: "Trayanov, Atanas L. (GSFC-610.1)[SCIENCE SYSTEMS AND APPLICATIONS INC]" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [GEOS-ESM/GEOSgcm_GridComp] Add DataLake mode in the lake component (#169)


@atrayano<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fatrayano&data=04%7C01%7CAtanas.L.Trayanov%40nasa.gov%7C7e0be1aef6ed44f5ff0f08da06900851%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637829512932032164%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=PHJs8a4UaxpU9O%2F6iVMQYjzg9Dk%2FVRchPuV%2FtmpZUR4%3D&reserved=0> yes this is 0-diff as anticipated. I would like to turn this on for more testing. Do we have an appropriate mask yet similar to the existing mode (Great Lakes and Caspian Sea)? Or anything I can test?

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGEOS-ESM%2FGEOSgcm_GridComp%2Fissues%2F169%23issuecomment-1068051861&data=04%7C01%7CAtanas.L.Trayanov%40nasa.gov%7C7e0be1aef6ed44f5ff0f08da06900851%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637829512932032164%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3Okj89aKYPPdq93b1jn3ZMrFtkgKySe1kNCWSBOqK5c%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAL6ZCVKN5QNTNF47LVKICMTVACM7RANCNFSM4KEN4OBA&data=04%7C01%7CAtanas.L.Trayanov%40nasa.gov%7C7e0be1aef6ed44f5ff0f08da06900851%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637829512932032164%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Jj%2B2ocg7if14o9n4AKN7QQBcbefRaTKxO8zPlRNWQfA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CAtanas.L.Trayanov%40nasa.gov%7C7e0be1aef6ed44f5ff0f08da06900851%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637829512932032164%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=fGmL9PaMBE%2BRI%2BZOfRShSwLIGueEdAvb8CL%2FZyEL8pk%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CAtanas.L.Trayanov%40nasa.gov%7C7e0be1aef6ed44f5ff0f08da06900851%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637829512932032164%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=BYqmEUU5q6bvloBuRg6zLb29UDY8Q123%2Fw6ytxw1Dgk%3D&reserved=0>.

**Comment by sanAkel** [comment]
@atrayano, @sdrabenh 
**FYI**:  `lake_sst_sic_EIGTHdeg.x` from [GMAO_Shared](https://github.com/GEOS-ESM/GMAO_Shared/tree/main/GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend), you should find it in your `install/bin/` can get you a **mask** and **data** over lakes.

**Comment by sdrabenh** [comment]
> @atrayano, @sdrabenh **FYI**: `lake_sst_sic_EIGTHdeg.x` from [GMAO_Shared](https://github.com/GEOS-ESM/GMAO_Shared/tree/main/GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend), you should find it in your `install/bin/` can get you a **mask** and **data** over lakes.

Thanks @sanAkel . Didn't refresh my page fast enough

**Comment by sanAkel** [comment]
> @atrayano yes this is 0-diff as anticipated. I would like to turn this on for more testing. Do we have an appropriate mask yet similar to the existing mode (Great Lakes and Caspian Sea)? Or anything I can test?

For this to happen:

>Do we have an appropriate mask yet similar to the existing mode (Great Lakes and Caspian Sea)?

we need a resolution to:

1. https://github.com/GEOS-ESM/GEOSgcm_GridComp/issues/534
2. and data set (binary or netcdf or ASCII or whatever!) for this to happen:

>I would like to turn this on for more testing.

**Comment by sanAkel** [comment]
> @atrayano, @sdrabenh **FYI**: `lake_sst_sic_EIGTHdeg.x` from [GMAO_Shared](https://github.com/GEOS-ESM/GMAO_Shared/tree/main/GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend), you should find it in your `install/bin/` can get you a **mask** and **data** over lakes.

For your convenience, instructions for generating mask and data are provided [here](https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/557#issuecomment-1069747761).
