### ISSUE TITLE
Negative mixing ratios returned by RAS

### ISSUE THREAD

**Issue by mmanyin** [GEOS-ESM/GEOSgcm_GridComp#177]
A long-standing problem with NOy in GMI chemistry was traced to an issue in RAS:  the convective transport  would sometimes return negative mixing ratios.   This problem of negative values is not just an issue for GMI;  it potentially impacts any chemical species that is "Friendly to MOIST".   To address this, a fix has been added to RAS, in which negative values are compensated for after every plume. **The fix is "off" by default, yielding zero-diff.**  I have a Git version of the code that is tested and ready for inclusion, but I wanted to give the GCM team a "heads up" before issuing a PR.
This code update involves GEOSgcm_GridComp, GEOSgcm_App and GEOSchem_GridComp.

**Comment by mathomp4** [comment]
@mmanyin Does the GF scheme have the same issue? I think the GCM by default runs GF and not RAS.

**Comment by mmanyin** [comment]
@mathomp4 The GF scheme handles negative tracers by replacing all negative values with a 'mintracer' value.  (Adding a PRINT statement prior to that, and simulating one day at C90 with StratChem, I see there are 65,000 times that a negative value gets overwritten by mintracer.)  I am waiting for the most recent edits to arrive from the FP code, before pursuing this issue.
