### ISSUE TITLE
Raster Code does not compile on desktop

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GEOSgcm_GridComp#183]
If you try and build the new raster code on the desktop with Intel Fortran and GNU C, you'll get an error:
```
gcc: error: unrecognized command line option ‘-qopenmp’; did you mean ‘-fopenmp’?
make[3]: *** [src/Components/@GEOSgcm_GridComp/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Shared/Raster/CMakeFiles/raster.dir/zip.c.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [src/Components/@GEOSgcm_GridComp/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Shared/Raster/CMakeFiles/raster.dir/all] Error 2
make[1]: *** [src/Components/@GEOSgcm_GridComp/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Shared/Raster/CMakeFiles/mkCatchParam.x.dir/rule] Error 2
make: *** [mkCatchParam.x] Error 2
```
The issue is that the `CMakeLists.txt` is assuming that the OpenMP flags for Fortran and C are the same:
https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/8097811a17b357061ac6ef8e5869f3dcc39ed330/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Shared/Raster/CMakeLists.txt#L27
Since `${this}` contains both C and Fortran code, we can't assume this.

The solution is, I think, to change this line to:
```cmake
target_link_libraries(${this} PRIVATE OpenMP::OpenMP_Fortran OpenMP::OpenMP_C)
```
Doing this does let things build, but I do not know how to test it. I will ask @smahanam to try it out as he knows how to run this code.

**Comment by mathomp4** [comment]
I'm going to ping @tclune so he can look at this. I can't actually really find any posts on the internet about a "mixed" C-Fortran library like this, but CMake seems to do things "right" (modulo the code actually running).

**Comment by tclune** [comment]
This is cleaner than what I would have provided.  There are ways to use cmake "generators" that are language specific.  Then you'd have 2 lines.  One that adds a flag to all Fortran sources and the other that adds a flag to al C sources.    But the namespace is a much better solution.

**Comment by smahanam** [comment]
Matt, make_bcs is fine, it works with OpenMP as before
