### ISSUE TITLE
GEOSldas tests for GCM developers or gatekeeper

### ISSUE THREAD

**Issue by gmao-rreichle** [GEOS-ESM/GEOSgcm_GridComp#243]
@wmputman @sdrabenh :

Last summer we had a group discussion (without Bill) about coordinating GCM and GEOSldas development.  The sticking point, of course, is that changes to SurfaceGridComp by GCM developers can change or break GEOSldas, without them realizing it.

At the time, we didn't quite resolve the issue, except to promise close coordination.  Since then, GEOSldas has come a long way, and it may be time to revisit the issue.

In particular, we may want to think about requiring GCM developers, or maybe just the GCM gatekeeper, to run the GEOSldas tests.  The latter are now reasonably easy to run and reasonably well documented on the [GEOSldas Wiki](https://github.com/GEOS-ESM/GEOSldas/wiki) -- although we still have to sort out a minor issue with how to load/link nccmp.

Note related issue #242 (nightly test for CatchCN).

**Comment by gmao-rreichle** [comment]
pinging @rdkoster

**Comment by gmao-rreichle** [comment]
At a meeting on 13 Apr 2020, @tclune suggested creating a group of land staff and assigning "ownership" of select files in Surface GridComp to that group.  
If a GCM GridComp pull request would modify any files owned by this new group, the pull request will need to be approved by the owners (in addition to approval by the GCM gatekeeper).  
Implementation of this concept is in process.

**Comment by tclune** [comment]
Replacing @wmputman  with @mathomp4 as the assignee.  (The person that will implement the changes.)  @wmputman should be added as the reviewer once the PR is submitted.

**Comment by gmao-rreichle** [comment]
@tclune @mathomp4 : I'm not sure I follow Tom's latest comment.  Maybe my previous comment was unclear, or I'm misunderstanding how assigning "ownership" works...
> Replacing @wmputman with @mathomp4 as the assignee. (The person that will implement the changes.)
I guess this pertains to implementing the "ownership" of select Surface GridComp files on github.com?  
> @wmputman should be added as the reviewer once the PR is submitted.
Not sure what PR would come of this issue.  Does the "ownership" assignment require a PR?

**Comment by tclune** [comment]
Sorry @gmao-rreichle I had not realized the earlier part of this thread.  Putting Bill back and opening a separate ticket for the CodeOwners bit.

**Comment by tclune** [comment]
Remaining issue of code owners opened under new ticket #266
