### ISSUE TITLE
Current develop branch doesn't run with GNU

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GEOSgcm_GridComp#258]
The nightly tests last night died running with GNU. It seems to be due to the addition of #174 into `develop`.

Running with Debug build we see:
```
At line 589 of file /discover/nobackup/mathomp4/SystemTests/builds/AGCM_GNU/CURRENT/GEOSgcm/src/Components/@GEOSgcm_GridComp/GEOS_GcmGridComp.F90
Fortran runtime error: Different CHARACTER lengths (7/8) in array constructor
```
where we have:
https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/a48b33e1735c8ee2356a46b847236a52d6c0c610/GEOS_GcmGridComp.F90#L586-L595

I'll need to write a tester to see what's happening here between the two compilers.

**Comment by mathomp4** [comment]
Oh boy. Okay, I see the issue. I might need to get the opinion @tclune on this one. This will be interesting...

**Comment by yvikhlya** [comment]
@mathomp4 @sdrabenh Oh, I think I went through this error before. It did not even compile with different string length in array constructor and failed circleci tests. But after fixing this, it did pass circleci tests. Not sure how this error could get back. Sorry about this. Let me double check and issue a fix.

**Comment by mathomp4** [comment]
@yvikhlya Actually, it is *usually* a compile-time fault. But since the array constructor is in a loop, it became a run-time issue. 

I have a solution for the issue now. But, in fixing it, a new bug popped up. One that is a bit more basic, so watch this space...

**Comment by yvikhlya** [comment]
@mathomp4 Oh, I see, I fixed some of array constructor errors, but not all of them, since i did not run with GNU, only compiled via circleci. I thought that if it passes mandatory tests, it is good to go.

**Comment by mathomp4** [comment]
Here's the fix I propose:
```fortran
      call MAPL_TerminateImport( GC,           &
         SHORT_NAME = [ character(len=(8)) ::  &
            'TAUA_'//suffix,                   &
            'ASYMP_'//suffix,                  &
            'SSALB_'//suffix ],                &
         CHILD      = OGCM,                    &
         RC=STATUS  )
      VERIFY_(STATUS)
```

**Comment by yvikhlya** [comment]
@mathomp4 Watch out, this may be not the only place where this happens. Same can be also in GEOS_DataatmGridComp.F90, GEOS_OgcmGridComp.f90, GEOS_ObioGridCmop.F90 and GEOS_OradbioGridComp.F90. Of course only GEOS_Gcm and GEOS_Ogcm matter for now, but why to leave bugs behind?

**Comment by yvikhlya** [comment]
@mathomp4 Ok, the same happens one more time in GEOS_GcmGridComp.F90 around line 1051. Who is going to make this fix?

**Comment by mathomp4** [comment]
@yvikhlya Yeah, I saw the second one. I don't think it matters as much, but I changed it too. Everything else in the PR seems okay in regards to the `suffix` code. 

I'm going to push a branch soon, but it's exposed something else that @bena-nasa is going to look at.

**Comment by yvikhlya** [comment]
@mathomp4 @atrayano a second one is actually protected by
```
if (do_obio /= 0)
```
and does not run in amip mode. I wonder why this terminate_import is not protected? Do you think it is a good idea to protect it?

**Comment by mathomp4** [comment]
> @mathomp4 @atrayano a second one is actually protected by
> 
> ```
> if (do_obio /= 0)
> ```
> 
> and does not run in amip mode. I wonder why this terminate_import is not protected? Do you think it is a good idea to protect it?

@yvikhlya That might be needed. I'm trying to get something to @bena-nasa and I think I have to do that or the model goes more nuts with GNU.

Note that whatever we figure out, we might need you (@yvikhlya ) to test all this in a coupled mode. :)

**Comment by yvikhlya** [comment]
@mathomp4 
> Note that whatever we figure out, we might need you (@yvikhlya ) to test all this in a coupled mode. :)

Oh yes, sure. If something breaks the coupled model I prefer to know this better sooner than later.

**Comment by atrayano** [comment]
@yvikhlya @mathomp4  I need to stare at the code to be 100% sure, but I believe it should be protected

**Comment by mathomp4** [comment]
@atrayano GNU was much happier when it was. Not protecting it seemed to cause the weird timer issue I was seeing...somehow.

**Comment by mathomp4** [comment]
@yvikhlya I think I got something that GNU liked in #260. I had to do a lot of `if(DO_OBIO/=0)` protections. Thus, I might have really broken the Coupled model. Can you test the branch in coupled mode to make sure it still works for you with the updates?
