### ISSUE TITLE
Minor changes and bug fixes for catchmentCN.F90, GEOS_SurfaceGridComp.rc and mkRestarts

### ISSUE THREAD

**Issue by gmao-jkolassa** [GEOS-ESM/GEOSgcm_GridComp#287]
A few minor changes and bug fixes need to be implemented for catchmentCN.F90, GEOS_SurfaceGridComp.rc and mkRestarts.
 
1. A new parameter RSWILT_CN needs to be added to the LandParams collection in SurfParams.F90 and passed to catchmentCN.F90. This is to replace the current hardcoding of RSWILT in Catchment-CN and allow for separate value choices of RSWILT for Catchment and Catchment-CN.

2. A default value for CO2_YEAR needs to be added in GEOS_SurfaceGridComp.rc. This is to avoid a warning message generated by the GEOSldas setup script when this parameter is left blank. 

3. The constraint to only use Haswell nodes in mkRestarts needs to be commented out.

cc: @gmao-rreichle , @smahanam , @gmao-jkolassa , @rdkoster

**Comment by gmao-rreichle** [comment]
FYI, additional changes may be needed as @gmao-jkolassa verifies the current github version of CatchCN vs. Fanwei's science-tested "LDASsa" version.
I think the edits should be 0-diff, at least so far.
I removed the "DNA" label - I think it's meant for "pull requests", not "issues".

**Comment by gmao-jkolassa** [comment]
Changes have been combined in a new GEOSgcm_GridComp branch "feature/jkolassa_#287_fixes". The updated code has been tested in a GEOSldas nightly test using branch "test/jkolassa_gcmGC_#287_fixes_nightly_test" (based off of GEOSldas "develop" branch and pointing at "feature/jkolassa_#287_fixes" branch for GEOSgcm_GridComp in Externals.cfg). The test results are:

Runtype    Clone Build Build Time Model Run/Compare Assim Run/Compare
-------    ----- ----- ---------- ----------------- -----------------
conus      pass  pass  12 min     pass/pass          -- / --        
global      --   pass   --        pass/pass         pass/FAIL       
globalcs    --   pass   --        pass/pass          -- / --        
globalcscn  --   pass   --        pass/pass          -- / --       

The failed global assimilation run comparison is unrelated to the changes made here, i.e., this test also fails using the "develop" branches of GEOSldas and GEOSgcm_GridComp.

An additional issue that has not yet been addressed and could be addressed in this branch is that land parameters LAND_FIX and FLWALPHA are not used in catchmentCN.F90, but probably should be.

1.	LAND_FIX: Controls choice between different calculations in catchment.F90. The equivalent calculations in catchmentCN.F90 correspond to a setting of LAND_FIX = .TRUE. for most calculations, but not for all. 
2.	FLWALPHA: Controls recharge from root-zone to surface. Currently hardcoded as 0.005 in catchmentCN.F90

**Comment by gmao-jkolassa** [comment]
I included additional changes related to the issues with LAND_FIX and FLWALPHA discussed above in GEOSgcm_GridComp branch “feature/jkolassa_#287_fixes”. Specific changes to  catchmentCN.F90 are 

1.	LAND_FIX and FLWALPHA are now read from SurfParams.F90. 
2.	‘If LAND_FIX’ statements have been wrapped around the respective code blocks to reflect equivalent expressions in catchment.F90. 
3.	The recharge from the root-zone to the surface – SRFLW – is now scaled by FLWALPHA instead of a hardcoded scaling factor of 0.005.

These changes have a significant non-zero-diff impact for several reasons.

1.	The previously hardcoded FLWALPHA term of 0.005 is very different from the FLWALPHA settings in either land parameter collection option, including the value of FLWALPHA = 0.04 that was used in the nightly test.
2.	Computations in the old catchmentCN.F90 corresponded to a LAND_FIX = .true. setting for most code blocks and a LAND_FIX = .false. setting for the constraint on QA and TC (ll. 1361 – 1395 in “develop” catchmentCN.F90), causing differences when a single LAND_FIX setting is used across catchmentCN.F90.
3.	In the old catchmentCN.F90 the engineering fix to dampen surface energy oscillations (ll. 1283 – 1308 in “develop” catchmentCN.F90) is never applied, because “using Helfand with viscous sublayer; don't need TC correction;” (Greg Walker’s comment in code). Making the code equivalent with catchment.F90 means that fix is applied for all vegetation types except ityp=1 or when LAND_FIX is true.

cc: @gmao-rreichle , @smahanam , @gmao-jkolassa , @rdkoster

**Comment by gmao-jkolassa** [comment]
Copying here Sarith's comment:

> On your below comment, CATCHCN and CATCH needed different parameter values, we picked 0.005 for CACTCHN after a calibration process many years ago.

In light of this, would it make sense to introduce a parameter FLWALPHA_CN (similar to what we did for RSWILT) to be able to control this scaling separately for Catch and CatchCN? Alternatively, I could generate a new land parameter collection that is intended to be used with CatchmentCN. This would avoid introducing too many parameters of the type XXXX_CN.

**Comment by gmao-jkolassa** [comment]
Generated a new GEOSgcm_GridComp branch (feature/jkolassa_#287_fixes) with the objectives of (1) being able to reproduce Fanwei Zeng's published LDASsa Catchment-CN simulations and (2) introducing two minor code modifications.

Modifications aimed at being able to reproduce Fanwei's Catchment-CN simulations affect the following files:

**SurfParams.F90:**
•	Introduced separate parameter collections for different land model choices that are being cross-checked against the land model choice
•	Catchment-CN collections include additional LAND_FIX_CN parameter that adjusts part of catchmentCN.F90 and GEOScatchCN_GridComp.F90 to reflect what was used in Fanwei Zeng’s experiments (to reproduce Fanwei's experiments, LAND_FIX_CN needs to be set to .FALSE.)

**catchmentCN.F90**
•	FLWALPHA and RSWILT are being read from SurfParams instead of being hardcoded
•	LAND_FIX_CN toggle is introduced as equivalent of LAND_FIX in catchment.F90 as well as to allow for changing code to what was used in Fanwei Zeng’s experiments. 

**GEOScatchCN_GridComp.F90**
•	Added LAND_FIX_CN read from SurfParams to toggle RDC formulation in order to match Fanwei Zeng’s experiments

**GEOS_SurfaceGridComp.F90**
•	Added LSM_CHOICE to SurfParams_init call

**dbg_cnlsm_offline.F90**
•	Added LSM_CHOICE to SurfParam_init call (hardcoded as Catchment_CN, since this is a CN specific routine)

The minor code modifications affect the following routines:

**GEOS_SurfaceGridComp.rc**
•	Added default value of -9999 for C02_YEAR

**mk_Restarts**
•	Removed contstraint to Haswell nodes


cc: @gmao-rreichle , @smahanam , @rdkoster , @biljanaorescanin , @gmao-jkolassa
