### ISSUE TITLE
Relaxed ocean and Atmospheric Replay

### ISSUE THREAD

**Issue by sanAkel** [GEOS-ESM/GEOSgcm_GridComp#322]
- [ ] capability needs to be added 
- [x] MOM6 plug: `subroutine Record` needs to be checked. Needed only if we want to a write restart while the run is still proceeding

**Comment by yvikhlya** [comment]
We need to have another tile file with lat-lon and MOM6 tripolar grids to interpolate SST and FRACI data for dual ocean set up.

**Comment by sanAkel** [comment]
> We need to have another tile file with lat-lon and MOM6 tripolar grids to interpolate SST and FRACI data for dual ocean set up.

Requesting: @atrayano 

@yvikhlya please add a reference to the `assignee` so he/she gets a notification. Thanks!

**Comment by sanAkel** [comment]
- [x] MOM6 plug: subroutine Record needs to be checked. Needed only if we want to a write restart while the run is still proceeding is **done**

**Comment by sanAkel** [comment]
The atmospheric **reply** will/should work as it does now with Dual Ocean.

Things to do for implementing dual ocean with MOM6:

- Add RUN2 in MOM6 plug that takes DELTA_SST as import from Guest Ocean GC; DELTA_SST is the difference between MOM's SST and SST(from _data_)

- We need to have a mechanism for relaxing MOM's SST, which could be accomplished in one of the following ways:

1. Using DELTA_SST (import from Guest Ocn), then compute an equivalent heat flux due to restoration and add that heat flux to **one** of the shortwave radiation bands (only one of either: vis dir/dif, nir dir/dif).
The way to compute _this_ heat flux would follow `coupled_driver/MOM_surface_forcing_gfdl.F90`, look for: `CS%restore_temp`

2. Compute the heat flux due to restoration as in above, but add it MOM's forcing (type), look for: `CS%restore_temp` in `coupled_driver/MOM_surface_forcing_gfdl.F90` this will require following the logicals in MOM and being able to access public (hopefully *not* private!) types.

**Comment by yvikhlya** [comment]
@sanAkel We already have a relaxation of MOM SST to data SST in guest (see DEL_TEMP field). Why do we need to do it different way in MOM6?

**Comment by sanAkel** [comment]
@yvikhlya the `DEL_TEMP` you are referring to, also as I did (with @atrayano on teams chat) with the name: `DELTA_SST` in above https://github.com/GEOS-ESM/GEOSgcm_GridComp/issues/322#issuecomment-668126722 is just the difference in SST (model - data). That's what is computed in guest: only the temperature difference for a relaxation time-scale.

**NOTE:** 
- MOM top level temperature is not touched in Guest Ocean GC, that as you know is done in Run2 of MOM(5) Plug. In fact, again, talking to @atrayano this is done _strictly_ speaking incorrectly! That is the MOM top level temperature is _brute force_ set to a _relaxed_ temperature (model SST + DEL_TEMP) with**out** changing or tracking heat flux due to this temperature adjustment.
- With MOM6, the 3D temperature is `private` so the same way of getting the 3D Temperature and setting T(:,:,1) to something as we do with MOM5 is **not** going to work.

Hopefully this clarifies why we need to do it differently with MOM6.

**Comment by yvikhlya** [comment]
> Hopefully this clarifies why we need to do it differently with MOM6.

Still not convinced why actually. May be because some of discussion went behind me.

**Comment by yvikhlya** [comment]
SST and fraci data on 360x210 grid are ready.

**Comment by sanAkel** [comment]
> SST and fraci data on 360x210 grid are ready.

@yvikhlya would you please point us to where these files are available. Thank you!

**Comment by yvikhlya** [comment]
> > SST and fraci data on 360x210 grid are ready.
> 
> @yvikhlya would you please point us to where these files are available. Thank you!

/home/yvikhlia/nobackup/coupled/Forcings/SST/MERRA2/360x210

**Comment by sanAkel** [comment]
@yvikhlya , Thank you!
