### ISSUE TITLE
Add melt_potential to MOM6 plug from:

### ISSUE THREAD

**Issue by sanAkel** [GEOS-ESM/GEOSgcm_GridComp#324]
- core/MOM_variables.F90
 - config_src/coupled_driver/ocean_model_MOM.F90 
   + add hooks in Ocean_sfc

**Comment by sanAkel** [comment]
**Note:** next run of MOM-5 of MOM-6 coupled model should have output:
- frazil
- freeze melt potential

**Need help** from @yvikhlya and @atrayano so we can write ocean/ice fields on GEOS/Tripolar grids

**Comment by sanAkel** [comment]
As pointed by @zhaobin74 we need to have the same TFREEZE_FORM for both CICE(4) and MOM6, i.e, we need to have `TFREEZE_FORM = "LINEAR"` in MOM_input or MOM_OVERRIDE.

**NOTE:** in the _long_ climate runs thus far with MOM6 coupled GEOS, we have `TFREEZE_FORM = "TEOS10"` 

This requires a change in our _default_ config: @yvikhlya

**Comment by sanAkel** [comment]
> **Note:** next run of MOM-5 of MOM-6 coupled model should have output:
> 
> * frazil
> * freeze melt potential
> 
> **Need help** from @yvikhlya and @atrayano so we can write ocean/ice fields on GEOS/Tripolar grids

This is already possible! So we are able to write output on tripolar grid using HISTORY.rc

**NOTE**: 
If using `geosgcm_ocn2d` collection in HISTORY.rc with MOM6, 
- some of the variables need to be left out since MOM6 does not output that MOM5 does,
- their names have changed.
- **MOM** should be replaced with **MOM6**

**Comment by yvikhlya** [comment]
> **MOM** should be replaced with **MOM6**

@sanAkel I think we should rename everything to MOM5 and MOM6 to make this distinct.

**Comment by yvikhlya** [comment]
@sanAkel As for TFREEZE_FROM option, I would suggest to combine all updates to MOM6 configs and submit them in one PR. I have update in diag_table (add thkcello to ocean_month_z) and we will probably have more updates. Let's do them  in one PR to save our time.

**Comment by sanAkel** [comment]
> > **MOM** should be replaced with **MOM6**
> 
> @sanAkel I think we should rename everything to MOM5 and MOM6 to make this distinct.

Let's leave MOM alone, _for now_ it is the default and eventually it will be phased out, then we don't have to deal with it!

**Comment by yvikhlya** [comment]
I have 360x180_360x210 tile file which allows to put tripolar MAPL collection from MOM6 runs onto lat-lon grid. Now we can do output of ocean/sea ice fields either on tripolar or on latlon grid.

**Comment by yvikhlya** [comment]
It looks like we don't need to do anything with TFREEZE_FORM, because the default value is LINEAR. My run has TEOS10 in MOM_override because I put it there after model crashed due to Tmin going out of bounds.

**Comment by sanAkel** [comment]
> It looks like we don't need to do anything with TFREEZE_FORM, because the default value is LINEAR. My run has TEOS10 in MOM_override because I put it there after model crashed due to Tmin going out of bounds.

True, @yvikhlya. 

That's why I took it off in `MOM_override`(branch we all are working for **this** issue)  https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/bugfix/sanAkel/issue324/GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/MOM6_GEOSPlug/mom6_app/360x210/MOM_override

**Comment by sanAkel** [comment]
Runs with above changes:
- MOM5 `~yvikhlia/aogcm/xxx_mom5`
- MOM6 `~yvikhlia/aogcm/xxx_mom6`
