### ISSUE TITLE
Orphan Point fix for MOM6 plug/Guest ocean

### ISSUE THREAD

**Issue by sanAkel** [GEOS-ESM/GEOSgcm_GridComp#325]
- so it works with MOM5 as well, instead of making HEATi(:,:,1) in Guest GC:

- add export of absorbed SW rad at 10m depth: SWN (surface) - 10m depth that is PEN_ocean 

- use that exported SW in Guest ocn to update orphan depth

- Merge variable `name` for ocean depth:
 o `OGCM_top_thickness` in Open Water 
 o  `OrphanDepth` in Guest ocean

**Comment by sanAkel** [comment]
Fixes for the orphan points (combined with fixes for https://github.com/GEOS-ESM/GEOSgcm_GridComp/issues/324):
https://github.com/GEOS-ESM/GEOSgcm_GridComp/tree/bugfix/sanAkel/issue324_PLUS_issue325

**Comment by sanAkel** [comment]
@yvikhlya the code is running and output from a _very_ short run is at:
`/discover/nobackup/sakella/test_m6/scratch/` Please check! Thanks!

**Comment by yvikhlya** [comment]
@sanAkel 
```
          PEN_OCN = PEN_OCN * WGHT
```
We don't need to do this in Guest, since this sets pen_ocn to 0 in orphan points, which we are trying to fix.

**Comment by sanAkel** [comment]
@yvikhlya 

- As for the 
>  bunch of other XXXe pointers since they are the same as XXX without 'e'.

they were already there! If they are not needed and nobody cares (I certainly do not!) please get rid of them!

- Reg. 
> why we need PEN_OCNe 

I added it just to be able to _check_ that HEATi(:,:,1) = net surface shortwave - PEN_OCN, i.e., this modification is giving same/similar, if not identical answer as before. You can get rid of it after checking with a MOM5 run as we agreed on.

- Thanks for getting rid of the weighting with `WGHT`. Somehow I missed its definition! ☹️ https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/631b986f2f8dba64c5510c9edc6db57d5179686c/GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/GuestOcean_GridComp.F90#L1167
