### ISSUE TITLE
Why is GuestOcean checking if it is replay

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/GEOSgcm_GridComp#337]
I was doing some development that involved running GEOS through the Jedi framework and working on the capability to run multiple model iterations from one execution by rewinding GEOS and restoring the previously saved state.

As I was doing this I was finding I could not rewind, integrate forward in time again and get back to the same state until Atanas reminded me that we have this private clock in the GuestOcean component. At some point, and I can not remember why, I put a check in that says, if you are doing replay, check if the private clock is ahead of the passed in clock and rewind the private clock back to the current time of the passed in clock. This is needed during replay as we have the extra predictor step. This takes place in the run method of GuestOcean around line 1018.
```
    call MAPL_GetResource(state,ReplayMode,  'REPLAY_MODE:',  default="NoReplay", RC=STATUS )
    if (trim(replayMode)=="Regular" ) then
       if (myTime > EndTime) then
          call ESMF_ClockSet(PrivateState%Clock,direction=ESMF_DIRECTION_REVERSE,rc=status)
          VERIFY_(status)
          do
            call ESMF_ClockAdvance(PrivateState%Clock,rc=status)
            VERIFY_(status)
            call ESMF_ClockGet(PrivateState%Clock,currTime=ct,rc=status)
            VERIFY_(status)
            if (ct==endTime) exit
          enddo
          call ESMF_ClockSet(PrivateState%Clock,direction=ESMF_DIRECTION_FORWARD,rc=status)
          VERIFY_(status)
          call ESMF_ClockGet( PrivateState%CLOCK, currTime=myTime, RC=STATUS)
          VERIFY_(status)
       end if
```

To get the Jedi test to pass I had to remove the restriction to only do this during replay. But as I was looking at this, I can't see why we need to check if it is replay at all. The only way the private clock could be ahead of the passed in clock is replay (and now Jedi). I can't think if why you would NOT want to rewind the private clock if it finds itself head of the passed in clock.

I thought Atanas said the only reason Guest even has a private clock is that you might want to run the ocean at a different timestep than the atmosphere so it might have to catch up. Indeed right after checking if we need to rewind the clock, the logic is, run the underlying ocean and advance my private clock to the time of the passed in clock. So there is no way the clock in Guest could ever find itself ahead of the clock passed in unless something like replay or Jedi has manipulated it so why have the logic to do the rewind only in replay.

In any case, I can't see any reason to have the extra check if we are doing replay and the rewind now has a 2nd case where it must happen. I am proposing removing the if statement to check if it is replay and just always rewind the internal clock if it finds itself ahead of the passed in clock.

**Comment by yvikhlya** [comment]
@bena-nasa This must have to do something with this 'dual ocean' logic. I am not an expert in how this works, Atanas should know this better.

**Comment by sanAkel** [comment]
@atrayano what about the leap frog time-stepping scheme in MOM5? Has that got to do anything with this _logic_?

**Comment by yvikhlya** [comment]
> @atrayano what about the leap frog time-stepping scheme in MOM5? Has that got to do anything with this _logic_?

We don't use leap frog time stepping.

**Comment by sanAkel** [comment]
> > @atrayano what about the leap frog time-stepping scheme in MOM5? Has that got to do anything with this _logic_?
> 
> 
> 
> We don't use leap frog time stepping.

Then, may be 2 level time step? 

Just to throw as a possible reason for @atrayano to recall?!

**Comment by sanAkel** [comment]
> @bena-nasa This must have to do something with this 'dual ocean' logic. I am not an expert in how this works, Atanas should know this better.

It should be possible with some digging through CVS logs / history who put this is in...

**Comment by bena-nasa** [comment]
I removed the if replay logic. The clock rewind has nothing to do with dual ocean both from code examination and a discussion with Atanas removing this check for replay is zero diff both in AMIP and coupled mode. Closing this issue.
