### ISSUE TITLE
Change OGCM to load MOM5 and MOM6 as DSO's (as opposed to linking)

### ISSUE THREAD

**Issue by tclune** [GEOS-ESM/GEOSgcm_GridComp#376]
The current mechanism for choosing which MOM to use in a coupled run is fragile and relies on LD_PRELOAD.   We believe that using shared object library interfaces (supported by ESMF) will be a more robust approach.

Known steps:

1. Remove MOM5 and MOM6 from dependencies of the parent components.
2. Add logic in parent components to derive child set services name and library path from config file
3. Modify `addChild()` to use different interface that specifies the setservices name and library path.
4. Make corresponding changes in GCM app
5. Make corresponding changes to MAPL `addChild()` if not already merged from previous work.
    - have `addChild()` append a trailing underscrore to the procedure name and make lower case.

**Comment by weiyuan-jiang** [comment]
If I remember correctly,  we will have to build the DSO for all the libraries, at lease those that MOMs depend on

**Comment by tclune** [comment]
OK - please try again first without doing that.   But if we must, we must.     It should just be FMS and MAPL.   I think the baselibs things generally already are.

**Comment by weiyuan-jiang** [comment]
@ are we going to use Gerhard's strategy to define an extra subroutine? like

 subroutine myModelSetServices(comp, rc)
   use ESMF
   use myModelMod
   type(ESMF_GridComp) :: comp
   integer, intent(out) :: rc
   call SetServices(comp, rc)
end subroutine

Can we use the module:subroutine name mangling?

**Comment by tclune** [comment]
It definitely needs to be outside the module,  I don't know that there is much value in using a wrapper vs just cut-and-paste of the procedure to after tho module.   I suppose Gerhard's approach avoids making the run methods public.

So yes - do it his way.     But do just call it SetServices.   The library name will indicate which component it is for.   Silly to have to specify it twice.

**Comment by weiyuan-jiang** [comment]
I don't think it will work for DSO to just use the name "SetServices". This name becomes global and DSO would not allow the same names. So we will have to use myModelSetServices

**Comment by tclune** [comment]
There should only be one SetServices in each DSO.   If we ever have a situation where that is not true, then we can adjust.     The idea is that the parent component should know as little as possible about the child component.    Knowing the path to the library is unavoidable.

**Comment by weiyuan-jiang** [comment]
It seems my branch feature/wjiang/mom_dso is working. It uses the same branches on MAPL and GEOSgcm_GridComp. @mathomp4 can you verify this for me? I just want to make sure I really run MOM.

**Comment by weiyuan-jiang** [comment]
my branch on GEOSgcm is the same feature/wjiang/mom_dso

**Comment by mathomp4** [comment]
@weiyuan-jiang It built just fine. So I set up a MOM6 run. I tried it two different ways. The default still has `LD_PRELOAD` though maybe it's not necessary anymore? 

Still, both failed with:
```
 Real*4 Resource Parameter: OCEAN_DT:450.000000
pe=00000 FAIL at line=00129    BaseProfiler.F90                         <Timer MOM6 should not start when empty:>
pe=00000 FAIL at line=01819    MAPL_Generic.F90                         <status=1>
pe=00000 FAIL at line=01502    MAPL_Generic.F90                         <needs informative message>
OCEANInitialize                                809
pe=00000 FAIL at line=01847    MAPL_Generic.F90                         <needs informative message>
pe=00000 FAIL at line=01502    MAPL_Generic.F90                         <needs informative message>
OGCMInitialize                                1207
pe=00000 FAIL at line=01847    MAPL_Generic.F90                         <needs informative message>
pe=00000 FAIL at line=01502    MAPL_Generic.F90                         <needs informative message>
GCMInitialize                                 1204
pe=00000 FAIL at line=01847    MAPL_Generic.F90                         <needs informative message>
pe=00000 FAIL at line=00566    MAPL_CapGridComp.F90                     <status=1>
pe=00000 FAIL at line=00859    MAPL_CapGridComp.F90                     <status=1>
pe=00000 FAIL at line=00357    MAPL_Cap.F90                             <status=1>
pe=00000 FAIL at line=00214    MAPL_Cap.F90                             <status=1>
pe=00000 FAIL at line=00160    MAPL_Cap.F90                             <status=1>
pe=00000 FAIL at line=00134    MAPL_Cap.F90                             <status=1>
pe=00000 FAIL at line=00032    GEOSgcm.F90                              <status=1>
Abort(-858993460) on node 0 (rank 0 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, -858993460) - process 0
```
Seems like a Timer issue?

**Comment by weiyuan-jiang** [comment]
The preload is no necessary any more. I believe the LD_LIBRARY_PATH is enough ( it is already set in gcm_run.j)

**Comment by mathomp4** [comment]
> The preload is no necessary any more. I believe the LD_LIBRARY_PATH is enough ( it is already set in gcm_run.j)

@weiyuan-jiang Okay. Once the timer/profiler issue is figured out and we can run, I can make a matching-named branch on GEOSgcm_App "undoing" the `LD_PRELOAD` business.

**Comment by mathomp4** [comment]
Another thing to consider: On macOS, these libraries will be `.dylib` and not `.so`. So we can't really rely on the file suffix. (Which I now realize is a bug in the *current* GEOSgcm_App as it assumes `.so`.)

**Comment by tclune** [comment]
If there is a PR can we move the discussion there to make it easier to see the relevant source code?

I think the ESMF routine should be wrapped and let MAPL do several things to the specified library:

1.  switch to lower case to procedure name
2. append trailing underscore to procedure name
3. append OS-dependent prefix to library name  (ala Matt's comment)

It is possible that 1 and 2 above should simply be that the MAPL routine assumes that the procedure is called `setservices_` and only does those steps if the user overrides with a non-default name.   Not wed either way on that.

**Comment by weiyuan-jiang** [comment]
Now I made a PR, we can see clear what I have changed. How to change CMakeLists.txt in MPAL to produce libMAPL.so too?

**Comment by sanAkel** [comment]
@tclune Can this issue be closed?
