### ISSUE TITLE
MOM6 coupled model debug build dies!

### ISSUE THREAD

**Issue by sanAkel** [GEOS-ESM/GEOSgcm_GridComp#380]
The`develop` (Nov, 23, 2020) with following:

> Checking status...
GEOSgcm                | (b) main
env                    | (t) v3.1.0 (DH)
cmake                  | (t) v3.3.0 (DH)
ecbuild                | (t) geos/v1.0.5 (DH)
NCEP_Shared            | (t) v1.1.0 (DH)
GMAO_Shared            | (t) v1.3.3 (DH)
MAPL                   | (t) v2.4.0 (DH)
FMS                    | (t) geos/2019.01.02+noaff.2 (DH)
GEOSgcm_GridComp       | (b) develop
FVdycoreCubed_GridComp | (t) v1.2.5 (DH)
fvdycore               | (t) geos/v1.1.3 (DH)
GEOSchem_GridComp      | (t) v1.4.1 (DH)
mom                    | (t) geos/5.1.0+1.1.1 (DH)
mom6                   | (t) geos/v1.1.0 (DH)
GEOSgcm_App            | (b) develop
UMD_Etc                | (t) v1.0.3 (DH)
CPLFCST_Etc            | (t) v1.0.1 (DH)

built `debug` : `parallel_build.csh -mepo -debug -develop`
dies. My log file is at:
`/discover/nobackup/sakella/new_config/FIX/debug/log.debug_23Nov2020-debug`

**Note**:

1. The same built `release` as with: `parallel_build.csh -mepo -develop` finishes _clean_. Log file is at: `/discover/nobackup/sakella/new_config/FIX/release/log.develop_23Nov2020-release`
2. I have not checked if this happens with MOM5 coupled model; in fact, I am not sure if MOM5 coupled model builds in debug mode. If it does not, by no means, I would **not** insist on it! As long as `release` version works! But with MOM6 we need `debug` AND `release` to work!

**Comment by sanAkel** [comment]
An update on:
**Do we need to have 3d fields in `diag_table`?**

Checked _stock_ MOM6 from https://github.com/NOAA-GFDL/MOM6-examples with https://github.com/NOAA-GFDL/MOM6-examples/tree/dev/gfdl/ocean_only/global_ALE/z case, built with same Intel 19.1.3, as in our case, with Debug flags **ON.** 

**It does not die when diag_table has no 3D fields. Whereas in our case, it does!**
 
Did following 4 tests. Saved logs at: `/discover/nobackup/sakella/MOM6-GFDL/MOM6-examples/ocean_only/global_ALE/z/`
 

1. 	optimized, diag_table with 3d fields: `log.repro_full-diag_table`
2. 	optimized, diag_table with **NO** 3d fields: `log.repro_No_z-diag_table`
3. 	debug, diag_table with 3d fields: `log.debug_full-diag_table`
4. 	debug, diag_table with **NO** 3d fields: `log.debug_No_z-diag_table`

You may notice that above log files for optimized and debug builds are not identical. I have been told by @marshallward that folks at GFDL are aware of this, and that results differ _slightly_ in the beginning and diverge after a _longer_ run; these runs were for 1day.

**Comment by mathomp4** [comment]
Note. I have a possible fix for at least some part of this. It's a change to CMake Intel Debug flags in MOM6:

https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/382

and FMS:

https://github.com/GEOS-ESM/FMS/pull/16

In my (limited) testing, both changes are needed. Note that we'll need @sanAkel, et al, to test this.
