### ISSUE TITLE
Bug in GEOS_SurfaceGridComp.F90: TA used in Run2 without MAPL_GetPointer

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GEOSgcm_GridComp#394]
It looks like @yvikhlya found a bug in GEOS_SurfaceGridComp.F90. Namely, there is this code in the Run2 procedure:

https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/eb7e1994a5169a285b10a93df3cecaad632fa7c5/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOS_SurfaceGridComp.F90#L5767-L5820

and specifically:

https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/eb7e1994a5169a285b10a93df3cecaad632fa7c5/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOS_SurfaceGridComp.F90#L5808-L5819

The fun part is, no where in Run2 is TA "gotten" as it were by `MAPL_GetPointer`. It's declared:

https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/eb7e1994a5169a285b10a93df3cecaad632fa7c5/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOS_SurfaceGridComp.F90#L4896

and then the next mention of it is line 5808.

The change came in with https://github.com/GEOS-ESM/GEOSgcm_GridComp/commit/4e3110e097500a64bac0069cc4ba82919c8fe04d with the commit message: "Merged with S2S-3 cvs tag". So I'm wondering if that CVS tag *does* have a `MAPL_GetPointer` that was never transferred to Git? Can @yvikhlya or @sanAkel take a look at that?

Also: I guess I'll ping/tag @gmao-rreichle as his name is around this code. And maybe @atrayano because, well, I get confused when we get near tiles.

**Comment by mathomp4** [comment]
Also mentioning @bena-nasa as he was also involved in SI Team OTRS Ticket 0111648

**Comment by gmao-rreichle** [comment]
This looks indeed like a bug to me.  Thanks, Yuri, for tracking it down. 

The good news is that the bug's impact is very minor.  The impacted code is part of the precip corrections algorithm -- in a nutshell,  in this block we're replacing the modeled precip with precip from a file, which is exercised in MERRA-2 (with older, presumably non-buggy s/w) and S2S (possibly with the buggy s/w) but not FP.  

The file only provides total precip.  The code in question disaggregates this into precip components based on the model precip.  The bug only kicks in when the total precip rate is very small (less than 0.1 mm/d) and in this case impacts whether precip falls as rain or snow.  Since TA wasn't defined, my guess is that for rates less than 0.1 mm/d it always snowed.  (Someone should tell Gary!)

I'm pretty sure that the bug was introduced when we tweaked the gory details of the precip corrections a little bit in conjunction with the introduction of icefall and freezing rain.  This was done by Justin at the time.

To fix the bug, I think we need something like the following statement at or near line 5738:
`call MAPL_GetPointer(IMPORT, TA , 'TA'   ,  RC=STATUS); VERIFY_(STATUS)`
But someone with more knowledge of MAPL needs to take a closer look before adopting this fix.

cc: @amolod @rdkoster

**Comment by weiyuan-jiang** [comment]
BUT it is got  after it is used. And it is EXPORT.  https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/eb7e1994a5169a285b10a93df3cecaad632fa7c5/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOS_SurfaceGridComp.F90#L5956

**Comment by mathomp4** [comment]
Ah. as @weiyuan-jiang says, maybe that line needs to be moved up? I guess if `TA` is never set in Run2, then maybe it would be the Export we'd want? I'll leave that to the experts here to figure out which `TA` would be wanted.

**Comment by gmao-rreichle** [comment]
There's also Line 7733, which resets TA.  Not sure what it does and how it relates to IMPORTs and EXPORTs:
[GEOSgcm_GridComp/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOS_SurfaceGridComp.F90 Line 7733](https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/eb7e1994a5169a285b10a93df3cecaad632fa7c5/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOS_SurfaceGridComp.F90#L7733)

within if blocks...
`       if(associated(TA))  TA = TH - (SH/MAPL_CP + DSH  *DTS)/CT`

**Comment by yvikhlya** [comment]
@mathomp4 @gmao-rreichle There are some other pointers in Run2 which are used, but not associated (for example QA). S2Sv3 tag also has this problem, so it was probably introduced while tweaking precip correction or other things in surface. Let me handle S2Sv3 after this issue is fixed in git.

**Comment by mathomp4** [comment]
> Since TA wasn't defined, my guess is that for rates less than 0.1 mm/d it always snowed. (Someone should tell Gary!)

I just saw this. Interesting! I wonder if it's visible.

**Comment by amolod** [comment]
hi all,

my recollection is that the TA import into sfc is the bottom model level’s temperature, exported from dyn.
if that is what should be used for this algorithm (ie., not TS), then the pointer should be defined and the
connection made to the value in the import state.

surf’s TA export is something else – its the air temp just above the skin (at the sfc pressure), interpolated
there by assuming constant theta in sfc layer.

it seems that we do have small precip always set to snow....

also – the code that M2 uses, AND the code that the currently running S2S (Version 2) uses do not have
this bug.

so indeed, impact VERY small.....

and again, i would advocate fixing this in Icarus+ model versions by grabbing TA from the import state
and allocating a pointer (also for QA if needed).

thanks!

andrea

**Comment by yvikhlya** [comment]
I see what happened now. Old precip correction scheme did not depend on import TA. There was only export TA in Run2, which is different from import TA. Then precip correction was changed and I merged a new one from Justin's  Jason tag in CVS into S2Sv3 tag. Somehow get import TA pointer was either missing in Jason tag or I lost it during the merge. Then I merged S2Sv3 tag into git. The initial commit in git had the old precip correction code. If nobody objects, I'll fix TA (and other pointers if necessary) and submit a PR. I'll fix S2Sv3 tag too.

**Comment by amolod** [comment]
sounds great yuri. good catch.

thanks

**Comment by sanAkel** [comment]
> I see what happened now. Old precip correction scheme did not depend on import TA. There was only export TA in Run2, which is different from import TA. Then precip correction was changed and I merged a new one from Justin's Jason tag in CVS into S2Sv3 tag. Somehow get import TA pointer was either missing in Jason tag or I lost it during the merge. Then I merged S2Sv3 tag into git. The initial commit in git had the old precip correction code. If nobody objects, I'll fix TA (and other pointers if necessary) and submit a PR. I'll fix S2Sv3 tag too.

👍 Please be sure to run your modified code via a debug build, in addition to optimized build. And also please follow the `check list` at https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/377#issuecomment-733833042 Thanks!

**Comment by gmao-rreichle** [comment]
Just for the record, I think this issue (394) was addressed in [fd7aeed](https://github.com/GEOS-ESM/GEOSgcm_GridComp/commit/fd7aeed653091b539c55e05064fcf52c37013d70) 
I'll comment and then immediately re-close the issue.
