### ISSUE TITLE
Array subscript out of bounds

### ISSUE THREAD

**Issue by yvikhlya** [GEOS-ESM/GEOSgcm_GridComp#395]
Following #394. After fixing the bug with TA pointer, the same set up crashes in OGCM with the error:

```
forrtl: severe (408): fort: (3): Subscript #1 of the array GCS has value 0 which is less than the lower bound of 1

Image              PC                Routine            Line        Source
GEOSgcm.x          0000000012317E5F  Unknown               Unknown  Unknown
GEOSgcm.x          000000000ED93E5A  geos_ogcmgridcomp        2242  GEOS_OgcmGridComp.F90
```

Corresponding code:

https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/eb7e1994a5169a285b10a93df3cecaad632fa7c5/GEOSogcm_GridComp/GEOS_OgcmGridComp.F90#L2242

This is the issue only in dual ocean mode, crashes debug build.

**Comment by atrayano** [comment]
@yvikhlya could you point me to your experiment setup. I need to check few values in the resource file

**Comment by yvikhlya** [comment]
@atrayano 
```
~yvikhlia/geos5/v10170_do
~yvikhlia/aogcm/v10170_do
```

**Comment by atrayano** [comment]
@yvikhlya thanks! I'll let you know what I find. From very quick code inspection, my top suspect is that the variable OBIO has not been changed and most likely still is zero.

**Comment by yvikhlya** [comment]
@atrayano It looks like OBIO is assigned only if(DO_OBIO /= 0)

https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/eb7e1994a5169a285b10a93df3cecaad632fa7c5/GEOSogcm_GridComp/GEOS_OgcmGridComp.F90#L233

In S2Sv3 tag else statement also has OBIO=MAPL_AddChild(...) Not sure where it was lost.

**Comment by yvikhlya** [comment]
@atrayano Ah! ObioSimpleGridComp was deleted and is not added as child if(DO_OBIO = 0)

**Comment by atrayano** [comment]
@yvikhlya I totally agree, but I do not think anything would trigger DO_OBIO to test "true". And the way I have coded the explicit calling of the children, OBIO is one of them. I can put put a simple protection in the loop around line 2242 to skip the iteration if a child Id is 0. This definitely will "fix"the error, but I want to think a little more if we are masking a bigger issue this way. I will get back to you by tomorrow

**Comment by atrayano** [comment]
I am almost sure that deleting ObioSimple is OK in general. And in that case protection against zero child Id would work

**Comment by yvikhlya** [comment]
ObioSimple was deleted because it did nothing (literally). We need to make sure that we don't step into same problem if one day we decide to put it back to do something useful.

**Comment by atrayano** [comment]
@yvikhlya This is excellent feedback. I know exactly what needs to be done. I'll create a PR either later tonight or by mid-morning tomorrow

**Comment by yvikhlya** [comment]
@atrayano I thought about combining this issue and #394 into same PR. Do you think it better to be two different PRs?

**Comment by sanAkel** [comment]
Thank you! @atrayano , @yvikhlya. Please think over it... I certainly advocate for a _clean_ (as I see it) that when `DO_OBIO=0` we have **NO** OBIO connectivity whatsoever! In other words, the model most not know/care for anything OBIO. After all this how we have other components' behavior!

**Comment by atrayano** [comment]
@yvikhlya This is an interesting suggestion. I can see pros and cons (if we need to undo one of them). Let me quickly run this by Tom and Matt in the morning

**Comment by yvikhlya** [comment]
I just want to make sure that dual ocean runs with debug build before pushing any updates. There may be more bugs which will crash the model there.
