### ISSUE TITLE
catchmentCN.F90 and GEOScatchCN_GridComp.F90 need review

### ISSUE THREAD

**Issue by JustinPerket** [GEOS-ESM/GEOSgcm_GridComp#40]
In discussion with @weiyuan-jiang, @fwzeng, @smahanam, it was pointed out that catchmentCN.F90 and GEOScatchCN_GridComp.F90 need to be compared with catchment.F90 and GEOScatch_GridComp.F90 for possible missed development to be manually ported 

For example, related issue: #34

**Comment by gmao-rreichle** [comment]
out of date, closing.
