### ISSUE TITLE
NOBM connectivity check

### ISSUE THREAD

**Issue by sanAkel** [GEOS-ESM/GEOSgcm_GridComp#400]
# Check 
If following variables are being passed over to the children (OBIO and ORAD):

FROCEAN
https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/e0cf9fabbe700c3e23571466f444973dd6b20e4e/GEOSogcm_GridComp/GEOS_OceanBioGeoChemGridComp/GEOS_OceanbiogeochemGridComp.F90#L317-L325

MASKO
https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/e0cf9fabbe700c3e23571466f444973dd6b20e4e/GEOSogcm_GridComp/GEOS_OceanBioGeoChemGridComp/GEOS_OceanbiogeochemGridComp.F90#L327-L335

remove USE_ODAS
https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/e0cf9fabbe700c3e23571466f444973dd6b20e4e/GEOSogcm_GridComp/GEOS_OceanBioGeoChemGridComp/GEOS_OceanbiogeochemGridComp.F90#L445-L473

# need exports from OBIO and ORAD, preferably on lat-lon grid:
- PCO2
- FCO2
- BIO
- PPDIATOM
- ...
- PPPHAEO
- DISCHARGE is already there
**Is everything ready for them to be exported??**

# Following imports and Exports to support GEOS_OradBioGridComp.F90 are needed:

COSZ
https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/e0cf9fabbe700c3e23571466f444973dd6b20e4e/GEOSogcm_GridComp/GEOS_OradBioGridComp/GEOS_OradBioGridComp.F90#L134-L141

FROCEAN
https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/e0cf9fabbe700c3e23571466f444973dd6b20e4e/GEOSogcm_GridComp/GEOS_OradBioGridComp/GEOS_OradBioGridComp.F90#L179-L186

# need exports, preferably on lat-lon grid:

- SWHEAT
- KPAR
- TIRRQ
- CDOMABSQ

Variables such as: 
MODIS Aerosols (Atmospheric Optics) that _Data Atmosphere_ cannot get from _real_ atmosphere should be **available** from data file(s) and Data Atmosphere has to provide them.

**Comment by sanAkel** [comment]
Following seems to be an **error**!

https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/0a4ddaf62aadc82e5870d8a5ae75a307fffbb3e3/GEOSogcm_GridComp/GEOS_OgcmGridComp.F90#L976

It should be `DO_DATAATM==1`??

**Comment by sanAkel** [comment]
> Following seems to be an **error**!
> 
> https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/0a4ddaf62aadc82e5870d8a5ae75a307fffbb3e3/GEOSogcm_GridComp/GEOS_OgcmGridComp.F90#L976
> 
> It should be `DO_DATAATM==1`??

per @gmao-croussea 
```
I don't think that is an error because when we run DATA ATM we import whats called DUSD, DUDP and DUWT
```

**Comment by yvikhlya** [comment]
> > Following seems to be an **error**!
> > https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/0a4ddaf62aadc82e5870d8a5ae75a307fffbb3e3/GEOSogcm_GridComp/GEOS_OgcmGridComp.F90#L976
> > 
> > It should be `DO_DATAATM==1`??
> 
> per @gmao-croussea
> 
> ```
> I don't think that is an error because when we run DATA ATM we import whats called DUSD, DUDP and DUWT
> ```

I doubt there should be any `if` there. Chemistry should provide these depositions.

**Comment by sanAkel** [comment]
> > > Following seems to be an **error**!
> > > https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/0a4ddaf62aadc82e5870d8a5ae75a307fffbb3e3/GEOSogcm_GridComp/GEOS_OgcmGridComp.F90#L976
> > > 
> > > It should be `DO_DATAATM==1`??
> > 
> > 
> > per @gmao-croussea
> > ```
> > I don't think that is an error because when we run DATA ATM we import whats called DUSD, DUDP and DUWT
> > ```
> 
> I doubt there should be any `if` there. Chemistry should provide these depositions.

I agree @yvikhlya This entire subroutine is called only when `DO_OBIO/=0` so we should take the `if ... endif` off. @gmao-esherman please let's remember!

**Comment by gmao-esherman** [comment]
> > > > Following seems to be an **error**!
> > > > https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/0a4ddaf62aadc82e5870d8a5ae75a307fffbb3e3/GEOSogcm_GridComp/GEOS_OgcmGridComp.F90#L976
> > > > 
> > > > It should be `DO_DATAATM==1`??
> > > 
> > > 
> > > per @gmao-croussea
> > > ```
> > > I don't think that is an error because when we run DATA ATM we import whats called DUSD, DUDP and DUWT
> > > ```
> > 
> > 
> > I doubt there should be any `if` there. Chemistry should provide these depositions.
> 
> I agree @yvikhlya This entire subroutine is called only when `DO_OBIO/=0` so we should take the `if ... endif` off. @gmao-esherman please let's remember!

Noted!

**Comment by sanAkel** [comment]
Since https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/401 is merged, so closing this issue. 

If @gmao-esherman, @gmao-croussea have any problems, open it again as needed.
