### ISSUE TITLE
Resolution-dependent surface O3 bias using FV3 in GCHP

### ISSUE THREAD

**Issue by lizziel** [GEOS-ESM/GEOSgcm_GridComp#48]
Hi there!
Earlier ths year I incorporated a mid-Feb 2019 version of MAPL and FV3 from the GMAO geosagcm develop branch into GCHP 12.5.0. The GEOS-Chem Support Team is now benchmarking this version. The 1-month benchmark results show unexpectedly elevated ozone across the Southern Ocean when comparing against GCHP 12.4.0 and GEOS-Chem Classic (GCC) 12.5.0. Here is the 1-month average surface O3 comparison with GCC 12.5.0:
<img width="1047" alt="gchp_vs_classic_o3_benchmark" src="https://user-images.githubusercontent.com/651947/63549642-cf4a4880-c4fe-11e9-8782-b522dccd7eab.png">

Further testing shows that the issue is originating in FV3. A GCHP run with all components off except advection shows the ozone bias, while a GCHP run with everything off does not.  Please note that the subtitles are not entirely correct in the plots: Ref is 12.4.0 while Dev is 12.5.0. So Ref is the old advection while Dev is the new advection used in the GCHP GCC plots above.

I output daily averages and see that the ozone steadily increases across the Southern Ocean throughout the month during the c48 benchmark run. 
<img width="748" alt="bench_10day_c48" src="https://user-images.githubusercontent.com/651947/63550546-e9852600-c500-11e9-8e26-1db9818ae0f9.png">
<img width="790" alt="bench_20day_c48" src="https://user-images.githubusercontent.com/651947/63550554-eab65300-c500-11e9-8fe8-c11ebc3f52c9.png">
<img width="755" alt="bench_30day_c48" src="https://user-images.githubusercontent.com/651947/63550561-f144ca80-c500-11e9-858d-52865ce67827.png">

Interestingly I never ran into this problem with my standard full chemistry c24 runs. Early test results indicate this is because the problem is resolution-dependent. Here is how my 12.5.0 end-of-month instantaneous surface ozone compares with 12.4.0 when run at c24. The differences outside of the Southern Ocean are expected given changes in emissions in the two versions:
<img width="731" alt="standard_c48_end-of-month" src="https://user-images.githubusercontent.com/651947/63551014-fbb39400-c501-11e9-94c2-ecc4c451b413.png">

Compare this to c48 after just 9 days:
<img width="693" alt="standard_c48_9day" src="https://user-images.githubusercontent.com/651947/63551033-0c640a00-c502-11e9-8e71-1de6260401f4.png">

It seems this is enough evidence to think there is something going on in the new version of FV3, possibly related to CFL given the resolution-dependency. I have additional tests in progress, including without the recent https://github.com/GEOS-ESM/GEOSgcm_GridComp/issues/13 bug fix (all benchmark runs done with this fix).

@wmputman , @tclune Thoughts?

**Comment by JiaweiZhuang** [comment]
"Science" questions:
- Does the advection in 12.5.0 still conserve mass? 
- How does the vertical profile look like? Does 12.5.0 have more stratospheric ozone moving down?  A lat-lev (zonal average) plot would be useful. 

Numerical questions:
- What's the resolution/grid of the input wind field? Do c24 and c48 read the same input data?
- Has the vector regridding algorithm changed? I know that scalar regridding is moving to use ESMF; but the vector part probably still uses FV3's own method? Would be useful to output the regridded wind components to see whether they stay the same after this version update.
- Does the new version of FV3 still uses a global mass fixer? Or it has a more advanced pressure fixer?

Software questions:
- How is FV3 being version-controlled in GEOS/MAPL? Is there a version number we can track? Does GEOS/MAPL keeps its own fork of FV3 , or imports it from an external repo?
- Is there an "official" version of FV3 we can refer to? The only public version of FV3 I am aware of is https://github.com/NOAA-EMC/fv3gfs. I have also used an early version of FV3 at https://www.gfdl.noaa.gov/cubed-sphere-quickstart/, but I don't think this one is actively updated.

**Comment by lizziel** [comment]
@JiaweiZhuang Some of these are GCHP-specific questions tat are better suited to GCHP GitHub, or simply stopping by my office (for this issue I prefer in-person). I can also answer questions about how GCHP will be interfacing with FV3 currently and in future versions. To be clear, FV3 is no longer part of this repository and 12.5 does not use this or the new repository directly.

**Comment by lizziel** [comment]
@tclune Do you prefer that this issue be moved to FVdycoreCubed_GridComp? My goal in creating the issue is eventually for feedback on whether other users of offline advection see something similar.

**Comment by JiaweiZhuang** [comment]
> Some of these are GCHP-specific questions that are better suited to GCHP GitHub

Sure, sorry for dumping questions here -- just wanted to make a checklist of all possible causes of error (not necessarily seeking for answers right now)

**Comment by lizziel** [comment]
@JiaweiZhuang No worries. All excellent questions. See also https://github.com/geoschem/gchp/issues/34.

**Comment by lizziel** [comment]
This issue is corrected by applying conservative regridding to input winds. We have traditionally used bilinear interpolation without issue, but moving to bilinear regridding with ESMF through MAPL introduced a bias. This will be corrected in GEOS-Chem 12.8.0.
