### ISSUE TITLE
OS agnostic `MOM6_GEOSPLUG` Label in GEOS_OceanGridComp.F90

### ISSUE THREAD

**Issue by sanAkel** [GEOS-ESM/GEOSgcm_GridComp#489]
I am testing on a mac which does not build `libMOM6_GEOSPlug.so`, but instead builds: `libMOM6_GEOSPlug.dylib` 

**NOTE**: difference in extensions.

On discover, no problems, but on mac, since `libMOM6_GEOSPlug.dylib` does not exist, following:
https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/f2272cbb6aa7b9e163ac3c4e41a910e94a90885b/GEOSogcm_GridComp/GEOS_OceanGridComp/GEOS_OceanGridComp.F90#L123 
did not work and I got an error message:
>pe=00003 FAIL at line=00145    BaseProfiler.F90                         <Timer <OCEAN> does not match start timer <MOM6>>

Clearly the extension `.so` should not be assumed for `libMOM6_GEOSPlug`.

@tclune helped identify this cause, he would be able to provide details. Thanks!

**Comment by tclune** [comment]
@weiyuan-jiang This issue should be split into 2.   One is to make the behavior OS agnostic.   The other is figuring out why the error trapping did not work correctly.   The latter is the priority.  (And not necessarily for @weiyuan-jiang )

**Comment by sanAkel** [comment]
@tclune I changed the `title` to reflect your ⬆️ suggestion, thank you! 

I guess we can get to 
>The other is figuring out why the error trapping did not work correctly. The latter is the priority. (And not necessarily for @weiyuan-jiang )

later ...

**Comment by weiyuan-jiang** [comment]
I think the trap should be in MAPL_AddChild. I will trace it

**Comment by sanAkel** [comment]
> I think the trap should be in MAPL_AddChild. I will trace it

Thanks!

**Comment by mathomp4** [comment]
Okay... I can think of a couple ways to do this. I'll need to discuss with @tclune

**Comment by weiyuan-jiang** [comment]
I tried to reproduce the errors by intentionally introducing a wrong shared lib like "MOM_GEOS5PLUGMOD: wrong.so".  The program correctly identified the line it crashes (line number may be different from yours).
pe=00105 FAIL at line=04947    MAPL_Generic.F90                         <status=506>
pe=00105 FAIL at line=00122    GEOS_OceanGridComp.F90                   <status=506>
pe=00105 FAIL at line=00145    BaseProfiler.F90                         <Timer <OCEAN> does not match start timer <MOM>>

Did the first two error lines appear in your error message? @sanAkel

**Comment by sanAkel** [comment]
> I tried to reproduce the errors by intentionally introducing a wrong shared lib like "MOM_GEOS5PLUGMOD: wrong.so". The program correctly identified the line it crashes (line number may be different from yours). pe=00105 FAIL at line=04947 MAPL_Generic.F90 <status=506> pe=00105 FAIL at line=00122 GEOS_OceanGridComp.F90 <status=506> pe=00105 FAIL at line=00145 BaseProfiler.F90 <Timer does not match start timer >
> 
> Did the first two error lines appear in your error message? @sanAkel

yes.

**Comment by weiyuan-jiang** [comment]
Sorry I didn't see it.  Then error tapping works fine. We need platform dependent defaults. @mathomp4 , have you come up good ideas?

**Comment by mathomp4** [comment]
@weiyuan-jiang Yes. I'm getting close. Trying to write some code for MAPL now

**Comment by mathomp4** [comment]
> Sorry I didn't see it. Then error tapping works fine. We need platform dependent defaults. @mathomp4 , have you come up good ideas?

@weiyuan-jiang I don't think it does. I think @tclune was thinking that the eventual ESMF calls should be checking not only `RC` but also `userRC` ?

**Comment by tclune** [comment]
The use reported by @sanAkel definitely reported the wrong error.

**Comment by weiyuan-jiang** [comment]
> 

I don't think so. The error code "506" means "ESMC_RC_ARG_BAD". In this case, the argument  sharedobj is  bad.
