### ISSUE TITLE
SCM crash with debug build in turbulence

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/GEOSgcm_GridComp#594]
@sanAkel, here is what I was talking about before:
While fixing a bug with MAPL that was affecting the single column model debug build (which I fixed, the original issue was this one: https://github.com/GEOS-ESM/MAPL/issues/1549), I immediately got hit with another crash this time in turbulence:
```
forrtl: error (75): floating point exception
Image              PC                Routine            Line        Source
GEOSgcm.x          000000000F463D0B  Unknown               Unknown  Unknown
libpthread-2.22.s  00002AAAD90E6C10  Unknown               Unknown  Unknown
GEOSgcm.x          000000000894DE1A  geos_turbulencegr        4296  GEOS_TurbulenceGridComp.F90
GEOSgcm.x          00000000088B4A4D  geos_turbulencegr        2728  GEOS_TurbulenceGridComp.F90
```
I setup the single column run with the following command:
```
./scm_setup --expdir /path_to_experiment --case arm_97jul --account your_account
```
and I was using the "main" branch of the GEOSgcm fixture with the following configuration:
```
GEOSgcm                | (b) main
env                    | (t) v3.13.0 (DH)
cmake                  | (t) v3.15.1 (DH)
ecbuild                | (t) geos/v1.2.0 (DH)
NCEP_Shared            | (t) v1.2.0 (DH)
GMAO_Shared            | (t) v1.5.4 (DH)
MAPL                   | (b) hotfix/bmauer/fixes-#1549
FMS                    | (t) geos/2019.01.02+noaff.8 (DH)
GEOSgcm_GridComp       | (t) v1.15.3 (DH)
FVdycoreCubed_GridComp | (t) v1.8.0 (DH)
fvdycore               | (t) geos/v1.4.0 (DH)
GEOSchem_GridComp      | (t) v1.9.2 (DH)
HEMCO                  | (t) geos/v2.2.3 (DH)
geos-chem              | (t) geos/v13.0.0-rc1 (DH)
GOCART                 | (t) v2.0.7 (DH)
GEOS_OceanGridComp     | (t) v1.1.0 (DH)
mom                    | (t) geos/5.1.0+1.2.0 (DH)
mom6                   | (t) geos/v2.0.3 (DH)
cice6                  | (t) geos/v0.0.1 (DH)
sis2                   | (t) geos/v0.0.1 (DH)
RRTMGP                 | (t) geos/v1.5+1.0.0 (DH)
GEOSgcm_App            | (t) v1.7.3 (DH)
UMD_Etc                | (t) v1.1.0 (DH)
CPLFCST_Etc            | (t) v1.0.1 (DH)
```

Strangely the release build runs fine. It is not clear to me the problem could be when looking at the turbulence code. I don't know if this is a problem with this particular setup, maybe a restart problem?

In any event I wanted to have a record of this. Note to test this you need MAPL version 2.21.3 or newer or you will hit the MAPL issue fixed as noted in the beginning of this issue.

**Comment by sanAkel** [comment]
@bena-nasa thanks for adding this issue. I got the same crash [as you report above](https://github.com/GEOS-ESM/GEOSgcm_GridComp/issues/594#issue-1263728988), that is with `debug` build and **after** updating to your latest fix (via https://github.com/GEOS-ESM/MAPL/commit/d46c2ed476db26b4d21ba52da5cb4256b1a6cf0e). I don't know much about `GEOS_TurbulenceGridComp.F90`. 

Checking with `release` ➡️ If that crashes, I will report.

**Comment by bena-nasa** [comment]
@sanAkel think release will work it did for me. I guess my only questions, is this an issue arm_97jul case only or a pervasive issue. I don't know much about turbulence either, so I'm not of much use.

**Comment by sanAkel** [comment]
> @sanAkel think release will work it did for me. I guess my only questions, is this an issue arm_97jul case only or a pervasive issue. I don't know much about turbulence either, so I'm not of much use.

@bena-nasa the same question:

>  I guess my only questions, is this an issue arm_97jul case only or a pervasive issue.

was asking by @mathomp4 and I tested the `debug` build after pulling in your (above) fix with another case: `merra_coare` and got **identical** error message and crashed- so its probably case insensitive. I can confirm that `release` version of the build runs without crashing (for `merra_coare`).

>  I don't know much about turbulence either, so I'm not of much use.

Maybe @narnold1 would like to look into it ...

**Comment by narnold1** [comment]
@sanAkel, try setting "TKE = 1e-6" at L4280, and add "TKE = max(1e-6, TKE)" at L4288.  If it's a divide-by-zero error, that should prevent it.
