### ISSUE TITLE
debug mode exposed an error that exists in optimized mode 

### ISSUE THREAD

**Issue by biljanaorescanin** [GEOS-ESM/GEOSgcm_GridComp#596]
Testing of bcs package in debug mode for NLv3 with EASE grid M09 exposed an error:
https://github.com/GEOS-ESM/GEOSldas/issues/552

Summarizing comments left on https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/576 here, so we can merge PR where comments were left:
> [GEOSgcm_GridComp/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/CombineRasters.F90](https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/9c3baa128d377b8a2c673f8bf8df31e3b1773b95/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/CombineRasters.F90#L343-L347)
> 
> Lines 343 to 347 in [9c3baa1](/GEOS-ESM/GEOSgcm_GridComp/commit/9c3baa128d377b8a2c673f8bf8df31e3b1773b95)
When line 344 is executed, Pix1 = -999 which leads to crash. It is exposed by debug mode but exists in optimized mode ( just does not crash) .

We may have to examine why it checks table 2 of pix2 but use table 1 of pix1
from @gmao-rreichle 
https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/576#issuecomment-1149117456
from @atrayano:
https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/576#issuecomment-1150086274

**Comment by weiyuan-jiang** [comment]
https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/1046239f980616615bc494d54228e35cbc38eba6/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/rasterize.H#L141-L153

We have seen a lot of print out like "undefined pixels".  If it succeeds,  "Rasterization completed successfully" would be printed out. Unfortunately, we didn't see that message for tag NL3 and M09 grid . @biljanaorescanin @gmao-rreichle @atrayano

**Comment by biljanaorescanin** [comment]
@weiyuan-jiang we either never come to that section or we never had this successful message written out. Not with any EASE grid (36,25,09,03) or with any CF (24,48,90,180,360 ...) options. I never had a run of boundary conditions that prints out "Rasterization completed successfully". Unfortunately, I can't double check in Larry's directory (was this ever run successfully?) for older BCS versions because he doesn't have saved output *.log or *.err files with his runs. But since tile files are zero diff I presume it didn't. 
I compared:
`/discover/nobackup/ltakacs/bcs/Icarus-NLv3/Icarus-NLv3_Ostia/CF0360x6C_CF0360x6C/CF0360x6C_CF0360x6C-Pfafstetter.til`
With my file and number of tiles is the same same goes for our catchment.def files.
