### ISSUE TITLE
need more descriptive for the offline mode

### ISSUE THREAD

**Issue by weiyuan-jiang** [GEOS-ESM/GEOSgcm_GridComp#610]
It is always confusing to use the number for different modes. Can we define some parameters for different modes? 

https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/4eaddafc6408d8308dd72ff8b1bfda0d2b84f870/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOScatch_GridComp/GEOS_CatchGridComp.F90#L789-L798

**Comment by weiyuan-jiang** [comment]
@gmao-rreichle , What are the better names for those 0, 1, 2?

**Comment by gmao-rreichle** [comment]
@weiyuan-jiang, as discussed offline (so to speak), I don't think this needs changing.  I recommend replacing the comments in the GEOS_CatchGridComp.F90 approximately here:
https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/4eaddafc6408d8308dd72ff8b1bfda0d2b84f870/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOScatch_GridComp/GEOS_CatchGridComp.F90#L117
with the help text (or some variation thereof) in GEOSldas_LDAS.rc file here:
https://github.com/GEOS-ESM/GEOSldas/blob/6211f3ec8283de340f704592f6b71b354ee912de/src/Applications/LDAS_App/GEOSldas_LDAS.rc#L14
These comments could also be added near L789 in GEOS_CatchGridComp.F90.

**Comment by gmao-rreichle** [comment]
#751 reorganizes the treatment of the OFFLINE_MODE rc variable and adds a comment pointing to the documentation in GEOSldas/src/Applications/LDAS_App/GEOSldas_LDAS.rc.
Closing this issue.
