### ISSUE TITLE
hyphen or underscore line

### ISSUE THREAD

**Issue by weiyuan-jiang** [GEOS-ESM/GEOSgcm_GridComp#625]
https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/cca38c1d79e2d4187259b0cf7cdba2dd1fbfc475/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/mkSMAPTilesPara_v2.F90#L122-L124

@gmao-rreichle Should we use this opportunity to make it consistent? GCM usually uses underscore line?

**Comment by gmao-rreichle** [comment]
@weiyuan-jiang,
Making things consistent is always good.
I took a very quick look at this program and noticed a couple of things:

1) EASEv2 M09 and M36 are treated as special cases, which is still odd to me.  There are also EASEv2 M01 and M03 grids, as well as EASE[v1] M25.  I don't understand why EASEv2 M09 and M36 should be any different.  That is, it's possible that we don't even need EASElabel if we really clean things up, or that we need EASElabel for the other EASEv[x] grids as well.

2) Could item 1) be related to the intermediate files generated for M09 and M36 that were non-0-diff in the bug fix PR?
See my comment here:
https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/601#issuecomment-1228999290

3) Note that `EASElabel` in mkSMAPTilesPara_v2.F90 is not initialized, and that the two subroutines defined in the program do not use an argument list of inputs/outputs.  The coding here is rather lazy and probably needs further cleanup beyond making the EASElabel values consistent with those used elsewhere. 

That's just a very quick review.  We can discuss more later if needed.  Thanks again.

**Comment by gmao-rreichle** [comment]
> 2. Could item 1) be related to the intermediate files generated for M09 and M36 that were non-0-diff in the bug fix PR?
>    See my comment here:
>    [non-zero-diff bug fixes in make_bcs package   #601 (comment)](https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/601#issuecomment-1228999290)

FYI, after talking with @biljanaorescanin, we agreed that the generation of the intermediate files for M09 and M36 should be commented out.  At the moment, these are not used.  It's possible (even likely) that the intermediate files are needed for the irrigation module, but this module is not ready and needs to be refurbished anyway.
