### ISSUE TITLE
Crash with S2S v3 restarts

### ISSUE THREAD

**Issue by sanAkel** [GEOS-ESM/GEOSgcm_GridComp#649]
I have 3 runs that have crashed while initializing.
1. Release:
    - optim build
    - debug build
2. Develop optim build

Here I will describe my **release debug** build of https://github.com/GEOS-ESM/GEOSgcm 
```
GEOSgcm                | (b) main
env                    | (t) v4.4.0 (DH)
cmake                  | (t) v3.18.0 (DH)
ecbuild                | (t) geos/v1.2.0 (DH)
NCEP_Shared            | (t) v1.2.0 (DH)
GMAO_Shared            | (t) v1.6.1 (DH)
MAPL                   | (t) v2.26.0 (DH)
FMS                    | (t) geos/2019.01.02+noaff.8 (DH)
GEOSgcm_GridComp       | (t) v1.17.0 (DH)
FVdycoreCubed_GridComp | (t) v1.12.1 (DH)
fvdycore               | (t) geos/v1.5.0 (DH)
GEOSchem_GridComp      | (t) v1.10.2 (DH)
HEMCO                  | (t) geos/v2.2.3 (DH)
geos-chem              | (t) geos/v13.0.0-rc1 (DH)
GOCART                 | (t) v2.1.0 (DH)
QuickChem              | (t) v1.0.0 (DH)
GEOS_OceanGridComp     | (t) v1.1.1 (DH)
mom                    | (t) geos/5.1.0+1.2.0 (DH)
mom6                   | (t) geos/v2.0.4 (DH)
cice6                  | (t) geos/v0.0.1 (DH)
sis2                   | (t) geos/v0.0.1 (DH)
GEOSradiation_GridComp | (t) v1.0.0 (DH)
RRTMGP                 | (t) geos/v1.5+1.0.0 (DH)
GEOSgcm_App            | (t) v1.8.0 (DH)
UMD_Etc                | (t) v1.1.0 (DH)
CPLFCST_Etc            | (t) v1.0.1 (DH)
```

Debug build (path follows below) seems to indicate a problem in
[FVdycore_GridCompMod.F90](https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/5c389124ffd8c7da1fd84564038e77201aef6b58/GEOSagcm_GridComp/GEOSsuperdyn_GridComp/FVdycore_GridComp/FVdycore_GridCompMod.F90#L2408-L2409). 

My restarts:
- They originate from S2S v3 1982/01/01. `/archive/u/gmaofcst/GEOS5.0/M2OCEAN_S2SV3//restarts//Y1982/restarts.e19820101_00z.tar`
- I regridded them _consistently_ with the remap utility that I built.  Config file: `/discover/nobackup/sakella/restarts/restarts_S2Sv3_14Oct2022/output_m6/remap_params.yaml`

Debug build path:
`/discover/nobackup/sakella/geosMom6/v10.23.0/GEOSgcm/install-Debug`

Log file:
`/discover/nobackup/sakella/cpld72L_1m_m6_Oct2022/debug-test1.log`

Appreciate any help to fix this problem!.Thanks!

**Comment by sanAkel** [comment]
Adding **one more data point**. I tried:
- `develop` and `optimized` build
- c12 x 5-deg case

To my surprise (and some ☮️ ) that worked! Of course, restarts and everything for this case originates from @mathomp4 
-- at least we have a case that (still) works and another that fails when the resolution and restarts are changed to what I described ⤴️ .

FWIW, log file for `c12 x 5-deg` is at: `/discover/nobackup/sakella/test_5deg/test1.log`

**Comment by sanAkel** [comment]
Following ⬆️ it became apparent to me that somehow my restarts got corrupted, and specifically `fvcore_internal_rst`.

I could successfully generate a _healthy_ set of restarts and get a 1-day run to finish okay.

FWIW I left the case that generated _bad_ restarts at: `/discover/nobackup/sakella/restarts/restarts_S2Sv3_14Oct2022/CORRUPTED_rst` for @weiyuan-jiang's interest!

For now, closing this issue!

**Comment by mathomp4** [comment]
I just saw this ticket and was going through it...but it seems to work...so huzzah!
