### ISSUE TITLE
Odd CircleCI behavior

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GEOSgcm_GridComp#65]
@pchakraborty Do you know why CircleCI seems to be acting a bit oddly:

https://circleci.com/gh/GEOS-ESM/GEOSgcm_GridComp

Like this one: https://circleci.com/gh/GEOS-ESM/GEOSgcm_GridComp/93 seemed to die instantly...

**Comment by pchakraborty** [comment]
@mathomp4 The branch hotfix/atrayano/#35_ordering_inside_MTR_bundle yesterday has been deleted, so can't tell for sure. But, the most likely reason is that that the branch was not sync-ed with master and was missing the CircleCI config.
