### ISSUE TITLE
mislabeled units for some CatchCNCLM45 variables in GEOS_CatchCNCLM45GridComp.F90

### ISSUE THREAD

**Issue by gmao-jkolassa** [GEOS-ESM/GEOSgcm_GridComp#659]
The units for several CatchCNCLM45 restart variables are mislabeled in the MAPL_AddInternalSpec calls in GEOS_CatchCNCLM45GridComp.F90. In each case the unit is listed as 'K'. The affected variables and their actual units are:

RHM [%]
WINDM [m/s]
RAINFM [kg/m^2/s]
SNOWFM [kg/m^2/s]
RUNSRFM [kg/m^2/s]
AR1M [1]

**Comment by gmao-jkolassa** [comment]
@weiyuan-jiang @gmao-rreichle

**Comment by gmao-rreichle** [comment]
@gmao-jkolassa, many thanks for the continued detective work.   It's probably best to start a new branch and PR just for this fix.  It's trivially 0-diff for the GCM and GEOSldas (assuming the test comparisons ignore metadata), so should be very easy to shepherd through the approval/merge process.

**Comment by gmao-rreichle** [comment]
addressed with #660
