### ISSUE TITLE
Avoid duplication of constants definition in CatchmentCNRst.F90

### ISSUE THREAD

**Issue by gmao-rreichle** [GEOS-ESM/GEOSgcm_GridComp#667]
CatchmentCNRst.F90 includes several hard-wired, orbit-related and CatchCN-specific constants:
https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/80c7acdba5d7b3518c44bdf14152826d76c16b7e/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/mk_restarts/CatchmentCNRst.F90#L10-L25
These constants exist in other places, e.g., 
https://github.com/GEOS-ESM/MAPL/blob/8bb4b4ae158e8f26400dadd4a5052d0814220d8e/generic/MAPL_Generic.F90#L4119
https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/80c7acdba5d7b3518c44bdf14152826d76c16b7e/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOScatchCN_GridComp/GEOScatchCNCLM40_GridComp/CLM40/clm_varpar.F90#L43

If at all possible, these constants should not be redefined in CatchmentCNRst.F90

**Comment by weiyuan-jiang** [comment]
Before moving things around, let's see how MAPL is going to solve this issue https://github.com/GEOS-ESM/MAPL/issues/1818

**Comment by weiyuan-jiang** [comment]
I suggest we move catchCN related parameters to LandShared just like catch @gmao-rreichle

**Comment by gmao-jkolassa** [comment]
For the Catchment-CN specific parameters that are originally parameters from CLM and that live in the modules clm_varpar.F90 and clm_varcon.F90, I would suggest to keep them there. Going forward, the plan is to keep the Catchment-CN implementation as modular as possible, so that when new CLM version are available it is less time-consuming to implement them in Catchment-CN. The CLM routines load their parameters from clm_varpar and clm_varcon, so in the interest of not having to change each CLM-routine, I would advocate for keeping the CLM-parameters in those two modules. For inside CatchmentCNRst.F90, we should be able to just import the CLM-parameters through the appropriate use-statements (@weiyuan-jiang I can take care of adding these in if you want).

**Comment by gmao-rreichle** [comment]
Thanks for the feedback.  I agree with @gmao-jkolassa that we should just add "use" statements that point to module clm_varpar.  Not sure how exactly we can resolve the different CatchCNCLM model versions. This may require a bit more tweaking of CatchmentCNRst.F90.
Re. the orbit constants:  A couple of years ago, Peter Norris introduced a new version of the orbit for the radiation GC.  I suspect the orbit constants in CatchmentCNRst.F90 are for the old orbit, and that Peter's new orbit version wasn't adopted in all GCs. This may require a discussion with Peter and Randy about changing the orbit parameterization in the land GC.

**Comment by mathomp4** [comment]
I'll wait for @dr0cloud to comment, but it looks like the four orbital parameters here do match the four in MAPL that are the defaults for those. So, that's good.

**Comment by dr0cloud** [comment]
Hi everyone, 
The below three files all hardcode in the parameters (ECCENTYRICITY,PERIHELION,OBLIQUITY,and EQUINOX) of the OLD orbital system and use them to calculate day length via compute_dayx() and orbit_create():
     CatchmentCNRst.F90, mk_CatchCNRestarts.F90, and mk_GEOSldasRestarts.F90.
What needs to happen is that they are upgraded to the NEW orbital system, which has a handy subroutine MAPL_SunGetDaylightDuration() in MAPL_SunMod. You can see an example of its use in the GridComps:
     GEOS_CatchCNCLM45GridComp.F90, and GEOS_CatchCNCLM40GridComp.F90.
I can code the correction if you want, but before I do, I hear from Jana that @weiyuan-jiang is doing a consolidation of the restart system. It would be nice if I didn't have to do the above fix in all three restart codes if there will become a single unified restart code. Please let me know about this ... SurfaceGC is not my usual stomping ground. Thanks, Peter.

**Comment by gmao-rreichle** [comment]
Many thanks, @dr0cloud, for taking a look!  I think that with your hints above, @weiyuan-jiang and @gmao-jkolassa should be able to get this done for the land group.  If you don't mind, we'll keep you cc'd on the forthcoming PR so you can double-check our work.
