### ISSUE TITLE
WSUB_ExtData.yaml points to non-existent files.

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/GEOSgcm_GridComp#776]
The current WSUB yaml file for extdata is simply wrong with the existing files

https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/develop/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/WSUB_ExtData.yaml

If you look in the above it uses this template:
/discover/nobackup/dbarahon/DEV/SWclim/SWclim_2005%m2.nc4
However, an ls of said directory shows this
```
(install-debug/bin) > ls /discover/nobackup/dbarahon/DEV/SWclim/
L132/                      L91/                       SWclim72lev_monthlies.nc4
L181/                      SWclim_132lev.nc4          SWclim_72lev.nc4
L72/                       SWclim_181lev.nc4          SWclim_91lev.nc4
```
So the template is simply not valid, this needs to be fixed.

**Comment by dbarahon** [comment]
The path to the files has been updated, fixing the issue.
