### ISSUE TITLE
land surface data increment application

### ISSUE THREAD

**Issue by JustinPerket** [GEOS-ESM/GEOSgcm_GridComp#84]
Per wiki guidelines, this is a notice for @wmputman  about a "new" feature @saraqzhang is working on. She's implementing increments to land surface variables in the ADAS. This work was in a decent stage of development prior to git, and work is now continuing on github.

**Comment by saraqzhang** [comment]
the implementation of LDAS increments to land surface variables are in the CatchmentGC. this branch has the new feature and merged with the GEOSgcm+GridComp develop branch up to date. 
the code has been tested ( in setting of LDAS, ADAS) with zero diff results.

**Comment by JustinPerket** [comment]
Closed with merge of https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/109
