### ISSUE TITLE
CatchCN CLM4.5 on SLES15

### ISSUE THREAD

**Issue by biljanaorescanin** [GEOS-ESM/GEOSgcm_GridComp#896]
During SLES15 testing our Nightly test for CatchCN CLM4.5 has floating point overflow error. 

@mathomp4  backtrace it to: 
==== backtrace (tid: 172041) ====
0 0x0000000000016910 __funlockfile()  ???:0
1 0x0000000000008e30 _ZGVbN4v_expf_sse4()  ???:0
2 0x0000000000059378 __cnfiremod_MOD_cnfirearea()  /discover/nobackup/mathomp4/SystemTests/builds/LDAS_GNUCONUS_SLES15/CURRENT/GEOSldas/src/Components/GEOSldas_GridComp/@GEOSgcm_GridComp/GEOSagcm_GridComp/GE
OSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOScatchCN_GridComp/GEOScatchCNCLM45_GridComp/CLM45/CNFireMod.F90:697
 
 
`Looks like the exponential blew out.`

https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/e2b79bdd24df30ab49889596f8fd97f4ab7271fb/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOScatchCN_GridComp/GEOScatchCNCLM45_GridComp/CLM45/CNFireMod.F90#L697

@gmao-rreichle @weiyuan-jiang @gmao-jkolassa

**Comment by mathomp4** [comment]
Okay. I can confirm the GCM shows the same thing:
```
[borgl167:16582:0:16582] Caught signal 8 (Floating point exception: floating-point overflow)
==== backtrace (tid:  16564) ====
 0 0x0000000000016910 __funlockfile()  ???:0
 1 0x0000000000008e30 _ZGVbN4v_expf_sse4()  ???:0
 2 0x0000000000059378 __cnfiremod_MOD_cnfirearea()  /discover/nobackup/mathomp4/SystemTests/builds/AGCM_GNUSLES15/CURRENT/GEOSgcm/src/Components/@GEOSgcm_GridComp/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOScatchCN_GridComp/GEOScatchCNCLM45_GridComp/CLM45/CNFireMod.F90:697
 3 0x00000000000b10fc __cnecosystemdynmod_MOD_cnecosystemdyn()  /discover/nobackup/mathomp4/SystemTests/builds/AGCM_GNUSLES15/CURRENT/GEOSgcm/src/Components/@GEOSgcm_GridComp/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOScatchCN_GridComp/GEOScatchCNCLM45_GridComp/CLM45/CNEcosystemDynMod.F90:255
```
I can think of flag tricks to try, though they'll all probably be non-zero-diff...

**Comment by gmao-rreichle** [comment]
@mathomp4 : Thanks for looking into this.  We are confident that we understand the reason for the CLM4.5 crash.  It's almost certainly caused by a calculation that involves `exp(-1e15)*something` and should be easy to fix.  I'm surprised we didn't run into this issue before.  It will probably require a hotfix of the GCM GridComp develop branch to get this to behave on SLES15.

**Comment by mathomp4** [comment]
Oh. Okay. Well, I have a possible workaround if not. You can compile CNFire.F90 as `-O1` if GNU Release. But a fix is better! 😄

**Comment by biljanaorescanin** [comment]
This issue will be addressed with this PR: https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/900

**Comment by biljanaorescanin** [comment]
Closing since issue was addressed.  We disabled CatchCN CLM 4.5 with merge of this PR https://github.com/GEOS-ESM/GEOSgcm_App/pull/601/
