### ISSUE TITLE
Remove `IS_FCST` and clean up associated logic in replay `TYPE`

### ISSUE THREAD

**Issue by sanAkel** [GEOS-ESM/GEOSgcm_GridComp#911]
Testing by @rtodling has found that these lines of code:
https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/8faac4966314203266371f2ae5bea3b77eb88302/GEOSagcm_GridComp/GEOS_AgcmGridComp.F90#L1730-L1734

are unnecessary, cause confusion and (potential) bugs. @atrayano is also aware of these lines of code.

@rtodling please add your notes as needed.

This `IS_FCST` must be removed also the above mentioned if block cleaned up.

```
IF
...
ENDIF
```

**Comment by tclune** [comment]
@sanAkel This is "assigned" to me.  I'm assuming that this is just meant to keep me informed rather than actually having me implement the fix?

**Comment by sanAkel** [comment]
@tclune, perhaps you would be to (re-) assign someone to it?

**Comment by mathomp4** [comment]
I mean, I could do the coding if I knew what is the "right" way to fix it. Could you and/or @rtodling let me know?

**Comment by rtodling** [comment]
Guys, before we change anything I suggest we do a little investigation on who is (if anyone) using this flag set to 1. If nobody is using the flag the simplest thing to do is to wipe out the implementation associated w/ the option 1.

I also strongly suggest talking to Larry Takacs, He might recall what the motivation might have been for distinguishing between a forecast and a "freerun" ... I sincerely cannot see the difference from an intellectual point of view, but clearly in the code lots of things happen that differ the two cases ... so not sure ... I suggest being careful w/ this.

**Comment by atrayano** [comment]
Ricardo, I agree that talking Larry Takacs is the right thing to do. I am more or less aware of the initial motivation: this has to do with the so-called bias correction done in Agcm. But again, the whole bias correction was Larry's idea, and the implementation is done also by him.

**Comment by sanAkel** [comment]
> Ricardo, I agree that talking Larry Takacs is the right thing to do. I am more or less aware of the initial motivation: this has to do with the so-called bias correction done in Agcm. But again, the whole bias correction was Larry's idea, and the implementation is done also by him.

Thanks @mathomp4, @rtodling, @atrayano 

Sometime - not "soon", I plan to have a chat with @lltakacs 
Reg replay. Will add this to my list of questions.
