### ISSUE TITLE
Cannot build GEOSgcm_GridComp

### ISSUE THREAD

**Issue by pchakraborty** [GEOS-ESM/GEOSgcm_GridComp#93]
On Discover, the build of the develop branch include #86 (62411e33a8f661e92191cdf271fb4e8e80673582) is failing. The build failed on CircleCI as well. The build succeeds if I roll back to 6963fa6283a27186b2b96389435b077844c029f1

Error message is

`/discover/nobackup/pchakrab/code/gmao/GEOSgcm/develop/src/Components/@GEOSgcm_GridComp/GEOSogcm_GridComp/GEOS_OgcmGridComp.F90(2194): error #6784: The number of actual arguments cannot be greater than the number of dummy arguments.   [ICE_NUDGING]
           call ice_nudging(FRO8d,         TIO8d,          &
----------------^
/discover/nobackup/pchakrab/code/gmao/GEOSgcm/develop/src/Components/@GEOSgcm_GridComp/GEOSogcm_GridComp/GEOS_OgcmGridComp.F90(980): remark #7712: This variable has not been used.   [J]
    integer                                 :: J
-----------------------------------------------^
/discover/nobackup/pchakrab/code/gmao/GEOSgcm/develop/src/Components/@GEOSgcm_GridComp/GEOSogcm_GridComp/GEOS_OgcmGridComp.F90(981): remark #7712: This variable has not been used.   [N_CHILDREN]
    integer                                 :: N_CHILDREN
-----------------------------------------------^
/discover/nobackup/pchakrab/code/gmao/GEOSgcm/develop/src/Components/@GEOSgcm_GridComp/GEOSogcm_GridComp/GEOS_OgcmGridComp.F90(990): remark #7712: This variable has not been used.   [PTR2D]
    real, pointer                           :: PTR2d   (:,:) => null()
-----------------------------------------------^
/discover/nobackup/pchakrab/code/gmao/GEOSgcm/develop/src/Components/@GEOSgcm_GridComp/GEOSogcm_GridComp/GEOS_OgcmGridComp.F90(992): remark #7712: This variable has not been used.   [HASTHISIMPORT]
    logical, allocatable                    :: hasThisImport(:)
-----------------------------------------------^
/discover/nobackup/pchakrab/code/gmao/GEOSgcm/develop/src/Components/@GEOSgcm_GridComp/GEOSogcm_GridComp/GEOS_OgcmGridComp.F90(1386): remark #7712: This variable has not been used.   [STROCNXB]
    real, pointer, dimension(:,:) :: STROCNXB => null()
-------------------------------------^
/discover/nobackup/pchakrab/code/gmao/GEOSgcm/develop/src/Components/@GEOSgcm_GridComp/GEOSogcm_GridComp/GEOS_OgcmGridComp.F90(1387): remark #7712: This variable has not been used.   [STROCNYB]
    real, pointer, dimension(:,:) :: STROCNYB => null()
-------------------------------------^
/discover/nobackup/pchakrab/code/gmao/GEOSgcm/develop/src/Components/@GEOSgcm_GridComp/GEOSogcm_GridComp/GEOS_OgcmGridComp.F90(1388): remark #7712: This variable has not been used.   [AICEU]
    real, pointer, dimension(:,:) :: AICEU => null()
-------------------------------------^
compilation aborted for /discover/nobackup/pchakrab/code/gmao/GEOSgcm/develop/src/Components/@GEOSgcm_GridComp/GEOSogcm_GridComp/GEOS_OgcmGridComp.F90 (code 1)
make[2]: *** [src/Components/@GEOSgcm_GridComp/GEOSogcm_GridComp/CMakeFiles/GEOSogcm_GridComp.dir/GEOS_OgcmGridComp.F90.o] Error 1
make[1]: *** [src/Components/@GEOSgcm_GridComp/GEOSogcm_GridComp/CMakeFiles/GEOSogcm_GridComp.dir/all] Error 2
make: *** [all] Error 2`

**Comment by mathomp4** [comment]
Ah. I think this was because a commit in the gcm fixture was approved but never merged. I merged it, that should fix it.

**Comment by pchakraborty** [comment]
Thanks Matt. It works now.
