### ISSUE TITLE
[NDSL] Radiation Coupling

### ISSUE THREAD

**Issue by FlorianDeconinck** [GEOS-ESM/GEOSgcm_GridComp#937]
Small 3-axis loop fitting the stencil pattern easily to port within the GFDL_1M 

Original code: [GEOS_GFDL_1M_InterfaceMod.F90:854](https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/db55c301840d98b788b0e17045510af726c0f555/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/GEOS_GFDL_1M_InterfaceMod.F90#L854)

Parent: https://github.com/GEOS-ESM/SMT-Nebulae/issues/57

---
- [ ] Port radiation coupling 3-axis loop to `pyMoist`

**Comment by FlorianDeconinck** [comment]
First port is done.

GEOS Physics runs at 32-bit, which means that the default `Float` of NDSL is ill-fitted for physics at large.

Port is ok but two fields are seeing ~5% of errors. Analysis is:
- Our system turns every calculation 32-bit, including literal, where we assume in Fortran there's implicit conversion happening
- We might be looking at data that have very low amplitude because the `moist` has nothing to do (e.g. low precipitation, everything is in liquid and no other tracers, etc.)

We need to explain those 5% a little further and/or generate a more interesting test case

**Comment by FlorianDeconinck** [comment]
Pushing back into backlog.

To re-open this task requires:
 - clear with Fortran dev the 32/64 literal issue (potentially using a py/fn test case)
 - clear with help of GMAO that our test case generating data is actually useful for Moist

**Comment by mattweil11** [comment]
Benchmarks before reintegration:

CPU: 3.572 ms
GPU: 0.568456 ms

~ 84% faster on GPU then on CPU

**Comment by FlorianDeconinck** [comment]
With new multi-modal metric and fixes to the precision of the constants, this is now passing all tests with HPC generated data.
