### ISSUE TITLE
[NDSL] Aer Activation

### ISSUE THREAD

**Issue by FlorianDeconinck** [GEOS-ESM/GEOSgcm_GridComp#942]
Port the Aer Activation component of Moist to `pyMoist`

Original code: [aer_actv_single_moment.F90:AerActivation](https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/db55c301840d98b788b0e17045510af726c0f555/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/aer_actv_single_moment.F90#L39)

Parent: https://github.com/GEOS-ESM/SMT-Nebulae/issues/57

---

- [x] Port Aer Activation to `pyMoist`
- [x] Generate dataset that actually looks at non-clamped values for `NACTL` and non-zero values for `NWFA`
- [x] Validate on finer dataset

--- 

Breakdown:

*_Aer_Activation_*
  - GetActFrac
    - ActFrac_Mat

**Comment by mattweil11** [comment]
State of Validation: 
- Data set not good enough for NACTL or NWFA validation
  - Line 285 in the Fortran acts as a clamping feature making NACTL hard to validate. Need different data set to truly validate NACTL.
  - NWFA validation data is always zero. No variance in the validation data.
- Variables from Fortran that are serialized that are never used in the Python Port according to the translate tests
  - AERO_F_DUST
  - AERO_F_ORGANIC
  - PLE
  - AERO_F_SOOT
  - ZLE0
  - ZL0
  - AERO_DENSITY
  - n_modes
  - SH
  - EVAP
  - KPBL
- Potential dead code in the Fortran:
  - Lines 238-244 (JM/IM loop) is reran in lines 252-257 (IM/JM/KM loop) so lines 238-244 does not do anything to our understanding
  - Literals 'WC', 'BB' and 'RAUX' are never used - Defined in lines 233-235

**Comment by FlorianDeconinck** [comment]
PR up: https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/964

**Comment by FlorianDeconinck** [comment]
4D fields are not handled by the Translate test. We are doing allocation by hand, resulting in not quantities in code and breaking of the auto-uploaded to GPU.

**Comment by mattweil11** [comment]
GPU and CPU benchmarks before reintegration:

CPU: 4.494 ms
GPU: 2.731 ms

~ 39.2 % faster on GPU then CPU

**Comment by FlorianDeconinck** [comment]
Handled 4D field by duplicating the IJK quantity factory and adding an extra dimension. This means we still need to do the Translate test memory translation by hand, but at least the code has been re-written with the full Quantity standard and is now ready for cpu/gpu.

**Comment by FlorianDeconinck** [comment]
Orchestration do not validate
GPU do not validate
`dace:cpu` do not validate

**Comment by FlorianDeconinck** [comment]
C180_L137 Run:
 - unstable, crashes w/ floating point exception after 1 calculation in Microphysics downstream
 - is it the numerics? is it the bridge?

**Comment by FlorianDeconinck** [comment]
Bridge fixed.
Stable for 48h of simulation on CPU.
Performance on par with Fortran on `gt:dace:cpu`

**Comment by FlorianDeconinck** [comment]
Test on GPU for lower resolution shows stability on `gt:dace:gpu`

**Comment by FlorianDeconinck** [comment]
Validation with multi-model metric + in-situ simulation shows good stability.
